//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.03 at 05:33:41 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://CIS/BIR/PUBL/2014/07", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.archu.gussoapintegration.gus;
