//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.23 at 06:14:09 PM CET 
//


package com.archu.gussoapintegration.integration.regon.fullreport.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dane"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="fiz_regon9" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="9"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2000"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_nazwaSkrocona" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="256"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataPowstania" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataRozpoczeciaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataWpisuDzialalnosciDoRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataZawieszeniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataWznowieniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataZaistnieniaZmianyDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataZakonczeniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataSkresleniaDzialalanosciZRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataOrzeczeniaOUpadlosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataZakonczeniaPostepowaniaUpadlosciowego" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzKraj_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzWojewodztwo_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzPowiat_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzGmina_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzKodPocztowy" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="12"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzMiejscowoscPoczty_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="7"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzMiejscowosc_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="7"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzUlica_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="5"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzNumerNieruchomosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="20"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzNumerLokalu" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzNietypoweMiejsceLokalizacji" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="160"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_numerTelefonu" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="18"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_numerWewnetrznyTelefonu" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="6"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_numerFaksu" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="18"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adresEmail" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adresStronyinternetowej" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzKraj_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzWojewodztwo_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzPowiat_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzGmina_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzMiejscowosc_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzMiejscowoscPoczty_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_adSiedzUlica_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="351"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dane"
})
@XmlRootElement(name = "root")
public class OsFizycznaDzialalnoscRolniczaRoot {

    @XmlElement(required = true)
    protected OsFizycznaDzialalnoscRolniczaData dane;

    /**
     * Gets the value of the dane property.
     * 
     * @return
     *     possible object is
     *     {@link OsFizycznaDzialalnoscRolniczaData }
     *     
     */
    public OsFizycznaDzialalnoscRolniczaData getDane() {
        return dane;
    }

    /**
     * Sets the value of the dane property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsFizycznaDzialalnoscRolniczaData }
     *     
     */
    public void setDane(OsFizycznaDzialalnoscRolniczaData value) {
        this.dane = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="fiz_regon9" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="9"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2000"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_nazwaSkrocona" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="256"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataPowstania" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataRozpoczeciaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataWpisuDzialalnosciDoRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataZawieszeniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataWznowieniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataZaistnieniaZmianyDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataZakonczeniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataSkresleniaDzialalanosciZRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataOrzeczeniaOUpadlosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataZakonczeniaPostepowaniaUpadlosciowego" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzKraj_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzWojewodztwo_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzPowiat_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzGmina_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzKodPocztowy" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="12"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzMiejscowoscPoczty_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="7"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzMiejscowosc_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="7"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzUlica_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="5"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzNumerNieruchomosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="20"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzNumerLokalu" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzNietypoweMiejsceLokalizacji" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="160"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_numerTelefonu" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="18"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_numerWewnetrznyTelefonu" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="6"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_numerFaksu" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="18"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adresEmail" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adresStronyinternetowej" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzKraj_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzWojewodztwo_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzPowiat_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzGmina_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzMiejscowosc_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzMiejscowoscPoczty_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_adSiedzUlica_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="351"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fizRegon9",
        "fizNazwa",
        "fizNazwaSkrocona",
        "fizDataPowstania",
        "fizDataRozpoczeciaDzialalnosci",
        "fizDataWpisuDzialalnosciDoRegon",
        "fizDataZawieszeniaDzialalnosci",
        "fizDataWznowieniaDzialalnosci",
        "fizDataZaistnieniaZmianyDzialalnosci",
        "fizDataZakonczeniaDzialalnosci",
        "fizDataSkresleniaDzialalanosciZRegon",
        "fizDataOrzeczeniaOUpadlosci",
        "fizDataZakonczeniaPostepowaniaUpadlosciowego",
        "fizAdSiedzKrajSymbol",
        "fizAdSiedzWojewodztwoSymbol",
        "fizAdSiedzPowiatSymbol",
        "fizAdSiedzGminaSymbol",
        "fizAdSiedzKodPocztowy",
        "fizAdSiedzMiejscowoscPocztySymbol",
        "fizAdSiedzMiejscowoscSymbol",
        "fizAdSiedzUlicaSymbol",
        "fizAdSiedzNumerNieruchomosci",
        "fizAdSiedzNumerLokalu",
        "fizAdSiedzNietypoweMiejsceLokalizacji",
        "fizNumerTelefonu",
        "fizNumerWewnetrznyTelefonu",
        "fizNumerFaksu",
        "fizAdresEmail",
        "fizAdresStronyinternetowej",
        "fizAdSiedzKrajNazwa",
        "fizAdSiedzWojewodztwoNazwa",
        "fizAdSiedzPowiatNazwa",
        "fizAdSiedzGminaNazwa",
        "fizAdSiedzMiejscowoscNazwa",
        "fizAdSiedzMiejscowoscPocztyNazwa",
        "fizAdSiedzUlicaNazwa"
    })
    public static class OsFizycznaDzialalnoscRolniczaData {

        @XmlElement(name = "fiz_regon9")
        protected String fizRegon9;
        @XmlElement(name = "fiz_nazwa")
        protected String fizNazwa;
        @XmlElement(name = "fiz_nazwaSkrocona")
        protected String fizNazwaSkrocona;
        @XmlElement(name = "fiz_dataPowstania")
        protected String fizDataPowstania;
        @XmlElement(name = "fiz_dataRozpoczeciaDzialalnosci")
        protected String fizDataRozpoczeciaDzialalnosci;
        @XmlElement(name = "fiz_dataWpisuDzialalnosciDoRegon")
        protected String fizDataWpisuDzialalnosciDoRegon;
        @XmlElement(name = "fiz_dataZawieszeniaDzialalnosci")
        protected String fizDataZawieszeniaDzialalnosci;
        @XmlElement(name = "fiz_dataWznowieniaDzialalnosci")
        protected String fizDataWznowieniaDzialalnosci;
        @XmlElement(name = "fiz_dataZaistnieniaZmianyDzialalnosci")
        protected String fizDataZaistnieniaZmianyDzialalnosci;
        @XmlElement(name = "fiz_dataZakonczeniaDzialalnosci")
        protected String fizDataZakonczeniaDzialalnosci;
        @XmlElement(name = "fiz_dataSkresleniaDzialalanosciZRegon")
        protected String fizDataSkresleniaDzialalanosciZRegon;
        @XmlElement(name = "fiz_dataOrzeczeniaOUpadlosci")
        protected String fizDataOrzeczeniaOUpadlosci;
        @XmlElement(name = "fiz_dataZakonczeniaPostepowaniaUpadlosciowego")
        protected String fizDataZakonczeniaPostepowaniaUpadlosciowego;
        @XmlElement(name = "fiz_adSiedzKraj_Symbol")
        protected String fizAdSiedzKrajSymbol;
        @XmlElement(name = "fiz_adSiedzWojewodztwo_Symbol")
        protected String fizAdSiedzWojewodztwoSymbol;
        @XmlElement(name = "fiz_adSiedzPowiat_Symbol")
        protected String fizAdSiedzPowiatSymbol;
        @XmlElement(name = "fiz_adSiedzGmina_Symbol")
        protected String fizAdSiedzGminaSymbol;
        @XmlElement(name = "fiz_adSiedzKodPocztowy")
        protected String fizAdSiedzKodPocztowy;
        @XmlElement(name = "fiz_adSiedzMiejscowoscPoczty_Symbol")
        protected String fizAdSiedzMiejscowoscPocztySymbol;
        @XmlElement(name = "fiz_adSiedzMiejscowosc_Symbol")
        protected String fizAdSiedzMiejscowoscSymbol;
        @XmlElement(name = "fiz_adSiedzUlica_Symbol")
        protected String fizAdSiedzUlicaSymbol;
        @XmlElement(name = "fiz_adSiedzNumerNieruchomosci")
        protected String fizAdSiedzNumerNieruchomosci;
        @XmlElement(name = "fiz_adSiedzNumerLokalu")
        protected String fizAdSiedzNumerLokalu;
        @XmlElement(name = "fiz_adSiedzNietypoweMiejsceLokalizacji")
        protected String fizAdSiedzNietypoweMiejsceLokalizacji;
        @XmlElement(name = "fiz_numerTelefonu")
        protected String fizNumerTelefonu;
        @XmlElement(name = "fiz_numerWewnetrznyTelefonu")
        protected String fizNumerWewnetrznyTelefonu;
        @XmlElement(name = "fiz_numerFaksu")
        protected String fizNumerFaksu;
        @XmlElement(name = "fiz_adresEmail")
        protected String fizAdresEmail;
        @XmlElement(name = "fiz_adresStronyinternetowej")
        protected String fizAdresStronyinternetowej;
        @XmlElement(name = "fiz_adSiedzKraj_Nazwa")
        protected String fizAdSiedzKrajNazwa;
        @XmlElement(name = "fiz_adSiedzWojewodztwo_Nazwa")
        protected String fizAdSiedzWojewodztwoNazwa;
        @XmlElement(name = "fiz_adSiedzPowiat_Nazwa")
        protected String fizAdSiedzPowiatNazwa;
        @XmlElement(name = "fiz_adSiedzGmina_Nazwa")
        protected String fizAdSiedzGminaNazwa;
        @XmlElement(name = "fiz_adSiedzMiejscowosc_Nazwa")
        protected String fizAdSiedzMiejscowoscNazwa;
        @XmlElement(name = "fiz_adSiedzMiejscowoscPoczty_Nazwa")
        protected String fizAdSiedzMiejscowoscPocztyNazwa;
        @XmlElement(name = "fiz_adSiedzUlica_Nazwa")
        protected String fizAdSiedzUlicaNazwa;

        /**
         * Gets the value of the fizRegon9 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizRegon9() {
            return fizRegon9;
        }

        /**
         * Sets the value of the fizRegon9 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizRegon9(String value) {
            this.fizRegon9 = value;
        }

        /**
         * Gets the value of the fizNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizNazwa() {
            return fizNazwa;
        }

        /**
         * Sets the value of the fizNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizNazwa(String value) {
            this.fizNazwa = value;
        }

        /**
         * Gets the value of the fizNazwaSkrocona property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizNazwaSkrocona() {
            return fizNazwaSkrocona;
        }

        /**
         * Sets the value of the fizNazwaSkrocona property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizNazwaSkrocona(String value) {
            this.fizNazwaSkrocona = value;
        }

        /**
         * Gets the value of the fizDataPowstania property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataPowstania() {
            return fizDataPowstania;
        }

        /**
         * Sets the value of the fizDataPowstania property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataPowstania(String value) {
            this.fizDataPowstania = value;
        }

        /**
         * Gets the value of the fizDataRozpoczeciaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataRozpoczeciaDzialalnosci() {
            return fizDataRozpoczeciaDzialalnosci;
        }

        /**
         * Sets the value of the fizDataRozpoczeciaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataRozpoczeciaDzialalnosci(String value) {
            this.fizDataRozpoczeciaDzialalnosci = value;
        }

        /**
         * Gets the value of the fizDataWpisuDzialalnosciDoRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataWpisuDzialalnosciDoRegon() {
            return fizDataWpisuDzialalnosciDoRegon;
        }

        /**
         * Sets the value of the fizDataWpisuDzialalnosciDoRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataWpisuDzialalnosciDoRegon(String value) {
            this.fizDataWpisuDzialalnosciDoRegon = value;
        }

        /**
         * Gets the value of the fizDataZawieszeniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataZawieszeniaDzialalnosci() {
            return fizDataZawieszeniaDzialalnosci;
        }

        /**
         * Sets the value of the fizDataZawieszeniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataZawieszeniaDzialalnosci(String value) {
            this.fizDataZawieszeniaDzialalnosci = value;
        }

        /**
         * Gets the value of the fizDataWznowieniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataWznowieniaDzialalnosci() {
            return fizDataWznowieniaDzialalnosci;
        }

        /**
         * Sets the value of the fizDataWznowieniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataWznowieniaDzialalnosci(String value) {
            this.fizDataWznowieniaDzialalnosci = value;
        }

        /**
         * Gets the value of the fizDataZaistnieniaZmianyDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataZaistnieniaZmianyDzialalnosci() {
            return fizDataZaistnieniaZmianyDzialalnosci;
        }

        /**
         * Sets the value of the fizDataZaistnieniaZmianyDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataZaistnieniaZmianyDzialalnosci(String value) {
            this.fizDataZaistnieniaZmianyDzialalnosci = value;
        }

        /**
         * Gets the value of the fizDataZakonczeniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataZakonczeniaDzialalnosci() {
            return fizDataZakonczeniaDzialalnosci;
        }

        /**
         * Sets the value of the fizDataZakonczeniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataZakonczeniaDzialalnosci(String value) {
            this.fizDataZakonczeniaDzialalnosci = value;
        }

        /**
         * Gets the value of the fizDataSkresleniaDzialalanosciZRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataSkresleniaDzialalanosciZRegon() {
            return fizDataSkresleniaDzialalanosciZRegon;
        }

        /**
         * Sets the value of the fizDataSkresleniaDzialalanosciZRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataSkresleniaDzialalanosciZRegon(String value) {
            this.fizDataSkresleniaDzialalanosciZRegon = value;
        }

        /**
         * Gets the value of the fizDataOrzeczeniaOUpadlosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataOrzeczeniaOUpadlosci() {
            return fizDataOrzeczeniaOUpadlosci;
        }

        /**
         * Sets the value of the fizDataOrzeczeniaOUpadlosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataOrzeczeniaOUpadlosci(String value) {
            this.fizDataOrzeczeniaOUpadlosci = value;
        }

        /**
         * Gets the value of the fizDataZakonczeniaPostepowaniaUpadlosciowego property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataZakonczeniaPostepowaniaUpadlosciowego() {
            return fizDataZakonczeniaPostepowaniaUpadlosciowego;
        }

        /**
         * Sets the value of the fizDataZakonczeniaPostepowaniaUpadlosciowego property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataZakonczeniaPostepowaniaUpadlosciowego(String value) {
            this.fizDataZakonczeniaPostepowaniaUpadlosciowego = value;
        }

        /**
         * Gets the value of the fizAdSiedzKrajSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzKrajSymbol() {
            return fizAdSiedzKrajSymbol;
        }

        /**
         * Sets the value of the fizAdSiedzKrajSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzKrajSymbol(String value) {
            this.fizAdSiedzKrajSymbol = value;
        }

        /**
         * Gets the value of the fizAdSiedzWojewodztwoSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzWojewodztwoSymbol() {
            return fizAdSiedzWojewodztwoSymbol;
        }

        /**
         * Sets the value of the fizAdSiedzWojewodztwoSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzWojewodztwoSymbol(String value) {
            this.fizAdSiedzWojewodztwoSymbol = value;
        }

        /**
         * Gets the value of the fizAdSiedzPowiatSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzPowiatSymbol() {
            return fizAdSiedzPowiatSymbol;
        }

        /**
         * Sets the value of the fizAdSiedzPowiatSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzPowiatSymbol(String value) {
            this.fizAdSiedzPowiatSymbol = value;
        }

        /**
         * Gets the value of the fizAdSiedzGminaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzGminaSymbol() {
            return fizAdSiedzGminaSymbol;
        }

        /**
         * Sets the value of the fizAdSiedzGminaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzGminaSymbol(String value) {
            this.fizAdSiedzGminaSymbol = value;
        }

        /**
         * Gets the value of the fizAdSiedzKodPocztowy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzKodPocztowy() {
            return fizAdSiedzKodPocztowy;
        }

        /**
         * Sets the value of the fizAdSiedzKodPocztowy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzKodPocztowy(String value) {
            this.fizAdSiedzKodPocztowy = value;
        }

        /**
         * Gets the value of the fizAdSiedzMiejscowoscPocztySymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzMiejscowoscPocztySymbol() {
            return fizAdSiedzMiejscowoscPocztySymbol;
        }

        /**
         * Sets the value of the fizAdSiedzMiejscowoscPocztySymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzMiejscowoscPocztySymbol(String value) {
            this.fizAdSiedzMiejscowoscPocztySymbol = value;
        }

        /**
         * Gets the value of the fizAdSiedzMiejscowoscSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzMiejscowoscSymbol() {
            return fizAdSiedzMiejscowoscSymbol;
        }

        /**
         * Sets the value of the fizAdSiedzMiejscowoscSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzMiejscowoscSymbol(String value) {
            this.fizAdSiedzMiejscowoscSymbol = value;
        }

        /**
         * Gets the value of the fizAdSiedzUlicaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzUlicaSymbol() {
            return fizAdSiedzUlicaSymbol;
        }

        /**
         * Sets the value of the fizAdSiedzUlicaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzUlicaSymbol(String value) {
            this.fizAdSiedzUlicaSymbol = value;
        }

        /**
         * Gets the value of the fizAdSiedzNumerNieruchomosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzNumerNieruchomosci() {
            return fizAdSiedzNumerNieruchomosci;
        }

        /**
         * Sets the value of the fizAdSiedzNumerNieruchomosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzNumerNieruchomosci(String value) {
            this.fizAdSiedzNumerNieruchomosci = value;
        }

        /**
         * Gets the value of the fizAdSiedzNumerLokalu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzNumerLokalu() {
            return fizAdSiedzNumerLokalu;
        }

        /**
         * Sets the value of the fizAdSiedzNumerLokalu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzNumerLokalu(String value) {
            this.fizAdSiedzNumerLokalu = value;
        }

        /**
         * Gets the value of the fizAdSiedzNietypoweMiejsceLokalizacji property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzNietypoweMiejsceLokalizacji() {
            return fizAdSiedzNietypoweMiejsceLokalizacji;
        }

        /**
         * Sets the value of the fizAdSiedzNietypoweMiejsceLokalizacji property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzNietypoweMiejsceLokalizacji(String value) {
            this.fizAdSiedzNietypoweMiejsceLokalizacji = value;
        }

        /**
         * Gets the value of the fizNumerTelefonu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizNumerTelefonu() {
            return fizNumerTelefonu;
        }

        /**
         * Sets the value of the fizNumerTelefonu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizNumerTelefonu(String value) {
            this.fizNumerTelefonu = value;
        }

        /**
         * Gets the value of the fizNumerWewnetrznyTelefonu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizNumerWewnetrznyTelefonu() {
            return fizNumerWewnetrznyTelefonu;
        }

        /**
         * Sets the value of the fizNumerWewnetrznyTelefonu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizNumerWewnetrznyTelefonu(String value) {
            this.fizNumerWewnetrznyTelefonu = value;
        }

        /**
         * Gets the value of the fizNumerFaksu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizNumerFaksu() {
            return fizNumerFaksu;
        }

        /**
         * Sets the value of the fizNumerFaksu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizNumerFaksu(String value) {
            this.fizNumerFaksu = value;
        }

        /**
         * Gets the value of the fizAdresEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdresEmail() {
            return fizAdresEmail;
        }

        /**
         * Sets the value of the fizAdresEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdresEmail(String value) {
            this.fizAdresEmail = value;
        }

        /**
         * Gets the value of the fizAdresStronyinternetowej property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdresStronyinternetowej() {
            return fizAdresStronyinternetowej;
        }

        /**
         * Sets the value of the fizAdresStronyinternetowej property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdresStronyinternetowej(String value) {
            this.fizAdresStronyinternetowej = value;
        }

        /**
         * Gets the value of the fizAdSiedzKrajNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzKrajNazwa() {
            return fizAdSiedzKrajNazwa;
        }

        /**
         * Sets the value of the fizAdSiedzKrajNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzKrajNazwa(String value) {
            this.fizAdSiedzKrajNazwa = value;
        }

        /**
         * Gets the value of the fizAdSiedzWojewodztwoNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzWojewodztwoNazwa() {
            return fizAdSiedzWojewodztwoNazwa;
        }

        /**
         * Sets the value of the fizAdSiedzWojewodztwoNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzWojewodztwoNazwa(String value) {
            this.fizAdSiedzWojewodztwoNazwa = value;
        }

        /**
         * Gets the value of the fizAdSiedzPowiatNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzPowiatNazwa() {
            return fizAdSiedzPowiatNazwa;
        }

        /**
         * Sets the value of the fizAdSiedzPowiatNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzPowiatNazwa(String value) {
            this.fizAdSiedzPowiatNazwa = value;
        }

        /**
         * Gets the value of the fizAdSiedzGminaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzGminaNazwa() {
            return fizAdSiedzGminaNazwa;
        }

        /**
         * Sets the value of the fizAdSiedzGminaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzGminaNazwa(String value) {
            this.fizAdSiedzGminaNazwa = value;
        }

        /**
         * Gets the value of the fizAdSiedzMiejscowoscNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzMiejscowoscNazwa() {
            return fizAdSiedzMiejscowoscNazwa;
        }

        /**
         * Sets the value of the fizAdSiedzMiejscowoscNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzMiejscowoscNazwa(String value) {
            this.fizAdSiedzMiejscowoscNazwa = value;
        }

        /**
         * Gets the value of the fizAdSiedzMiejscowoscPocztyNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzMiejscowoscPocztyNazwa() {
            return fizAdSiedzMiejscowoscPocztyNazwa;
        }

        /**
         * Sets the value of the fizAdSiedzMiejscowoscPocztyNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzMiejscowoscPocztyNazwa(String value) {
            this.fizAdSiedzMiejscowoscPocztyNazwa = value;
        }

        /**
         * Gets the value of the fizAdSiedzUlicaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizAdSiedzUlicaNazwa() {
            return fizAdSiedzUlicaNazwa;
        }

        /**
         * Sets the value of the fizAdSiedzUlicaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizAdSiedzUlicaNazwa(String value) {
            this.fizAdSiedzUlicaNazwa = value;
        }

    }

}
