//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 05:53:32 PM CET 
//


package com.archu.gussoapintegration.integration.regon.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dane" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="lokpraw_pkdKod" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="5"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_pkdNazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_pkdPrzewazajace" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dane"
})
@XmlRootElement(name = "root")
public class JednLokalnaOsPrawnejPkdRoot {

    protected List<JednLokalnaOsPrawnejPkdData> dane;

    /**
     * Gets the value of the dane property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dane property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDane().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JednLokalnaOsPrawnejPkdData }
     * 
     * 
     */
    public List<JednLokalnaOsPrawnejPkdData> getDane() {
        if (dane == null) {
            dane = new ArrayList<JednLokalnaOsPrawnejPkdData>();
        }
        return this.dane;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lokpraw_pkdKod" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="5"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_pkdNazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_pkdPrzewazajace" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lokprawPkdKod",
        "lokprawPkdNazwa",
        "lokprawPkdPrzewazajace"
    })
    public static class JednLokalnaOsPrawnejPkdData {

        @XmlElement(name = "lokpraw_pkdKod")
        protected String lokprawPkdKod;
        @XmlElement(name = "lokpraw_pkdNazwa")
        protected String lokprawPkdNazwa;
        @XmlElement(name = "lokpraw_pkdPrzewazajace")
        protected String lokprawPkdPrzewazajace;

        /**
         * Gets the value of the lokprawPkdKod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawPkdKod() {
            return lokprawPkdKod;
        }

        /**
         * Sets the value of the lokprawPkdKod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawPkdKod(String value) {
            this.lokprawPkdKod = value;
        }

        /**
         * Gets the value of the lokprawPkdNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawPkdNazwa() {
            return lokprawPkdNazwa;
        }

        /**
         * Sets the value of the lokprawPkdNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawPkdNazwa(String value) {
            this.lokprawPkdNazwa = value;
        }

        /**
         * Gets the value of the lokprawPkdPrzewazajace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawPkdPrzewazajace() {
            return lokprawPkdPrzewazajace;
        }

        /**
         * Sets the value of the lokprawPkdPrzewazajace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawPkdPrzewazajace(String value) {
            this.lokprawPkdPrzewazajace = value;
        }

    }

}
