//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 05:48:35 PM CET 
//


package com.archu.gussoapintegration.integration.regon.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dane"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="lokfiz_regon14" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="14"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2000"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_silosID" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_silos_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_dataPowstania" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_dataRozpoczeciaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_dataWpisuDoRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_dataZawieszeniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_dataWznowieniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_dataZaistnieniaZmiany" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_dataZakonczeniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_dataSkresleniaZRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzKraj_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzWojewodztwo_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzPowiat_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzGmina_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzKodPocztowy" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="12"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzMiejscowoscPoczty_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="7"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzMiejscowosc_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="7"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzUlica_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="5"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzNumerNieruchomosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="20"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzNumerLokalu" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzNietypoweMiejsceLokalizacji" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="256"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzKraj_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzWojewodztwo_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzPowiat_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzGmina_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzMiejscowosc_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzMiejscowoscPoczty_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_adSiedzUlica_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="350"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_FormaFinansowania_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="240"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_FormaFinansowania_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_dataWpisuDoRejestruEwidencji" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="30"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_numerwRejestrzeEwidencji" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="50"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_OrganRejestrowy_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="9"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_RodzajRejestru_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_OrganRejestrowy_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="240"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_RodzajRejestru_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="240"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfizC_NiePodjetoDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean"&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dane"
})
@XmlRootElement(name = "root")
public class JednLokalnaOsFizycznejRoot {

    @XmlElement(required = true)
    protected JednLokalnaOsFizycznejData dane;

    /**
     * Gets the value of the dane property.
     * 
     * @return
     *     possible object is
     *     {@link JednLokalnaOsFizycznejData }
     *     
     */
    public JednLokalnaOsFizycznejData getDane() {
        return dane;
    }

    /**
     * Sets the value of the dane property.
     * 
     * @param value
     *     allowed object is
     *     {@link JednLokalnaOsFizycznejData }
     *     
     */
    public void setDane(JednLokalnaOsFizycznejData value) {
        this.dane = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lokfiz_regon14" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="14"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2000"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_silosID" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_silos_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_dataPowstania" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_dataRozpoczeciaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_dataWpisuDoRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_dataZawieszeniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_dataWznowieniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_dataZaistnieniaZmiany" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_dataZakonczeniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_dataSkresleniaZRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzKraj_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzWojewodztwo_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzPowiat_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzGmina_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzKodPocztowy" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="12"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzMiejscowoscPoczty_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="7"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzMiejscowosc_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="7"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzUlica_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="5"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzNumerNieruchomosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="20"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzNumerLokalu" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzNietypoweMiejsceLokalizacji" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="256"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzKraj_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzWojewodztwo_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzPowiat_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzGmina_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzMiejscowosc_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzMiejscowoscPoczty_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_adSiedzUlica_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="350"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_FormaFinansowania_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="240"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_FormaFinansowania_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_dataWpisuDoRejestruEwidencji" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="30"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_numerwRejestrzeEwidencji" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="50"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_OrganRejestrowy_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="9"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_RodzajRejestru_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_OrganRejestrowy_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="240"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_RodzajRejestru_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="240"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfizC_NiePodjetoDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean"&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lokfizRegon14",
        "lokfizNazwa",
        "lokfizSilosID",
        "lokfizSilosNazwa",
        "lokfizDataPowstania",
        "lokfizDataRozpoczeciaDzialalnosci",
        "lokfizDataWpisuDoRegon",
        "lokfizDataZawieszeniaDzialalnosci",
        "lokfizDataWznowieniaDzialalnosci",
        "lokfizDataZaistnieniaZmiany",
        "lokfizDataZakonczeniaDzialalnosci",
        "lokfizDataSkresleniaZRegon",
        "lokfizAdSiedzKrajSymbol",
        "lokfizAdSiedzWojewodztwoSymbol",
        "lokfizAdSiedzPowiatSymbol",
        "lokfizAdSiedzGminaSymbol",
        "lokfizAdSiedzKodPocztowy",
        "lokfizAdSiedzMiejscowoscPocztySymbol",
        "lokfizAdSiedzMiejscowoscSymbol",
        "lokfizAdSiedzUlicaSymbol",
        "lokfizAdSiedzNumerNieruchomosci",
        "lokfizAdSiedzNumerLokalu",
        "lokfizAdSiedzNietypoweMiejsceLokalizacji",
        "lokfizAdSiedzKrajNazwa",
        "lokfizAdSiedzWojewodztwoNazwa",
        "lokfizAdSiedzPowiatNazwa",
        "lokfizAdSiedzGminaNazwa",
        "lokfizAdSiedzMiejscowoscNazwa",
        "lokfizAdSiedzMiejscowoscPocztyNazwa",
        "lokfizAdSiedzUlicaNazwa",
        "lokfizFormaFinansowaniaNazwa",
        "lokfizFormaFinansowaniaSymbol",
        "lokfizDataWpisuDoRejestruEwidencji",
        "lokfizNumerwRejestrzeEwidencji",
        "lokfizOrganRejestrowySymbol",
        "lokfizRodzajRejestruSymbol",
        "lokfizOrganRejestrowyNazwa",
        "lokfizRodzajRejestruNazwa",
        "lokfizCNiePodjetoDzialalnosci"
    })
    public static class JednLokalnaOsFizycznejData {

        @XmlElement(name = "lokfiz_regon14")
        protected String lokfizRegon14;
        @XmlElement(name = "lokfiz_nazwa")
        protected String lokfizNazwa;
        @XmlElement(name = "lokfiz_silosID")
        protected Integer lokfizSilosID;
        @XmlElement(name = "lokfiz_silos_Nazwa")
        protected String lokfizSilosNazwa;
        @XmlElement(name = "lokfiz_dataPowstania")
        protected String lokfizDataPowstania;
        @XmlElement(name = "lokfiz_dataRozpoczeciaDzialalnosci")
        protected String lokfizDataRozpoczeciaDzialalnosci;
        @XmlElement(name = "lokfiz_dataWpisuDoRegon")
        protected String lokfizDataWpisuDoRegon;
        @XmlElement(name = "lokfiz_dataZawieszeniaDzialalnosci")
        protected String lokfizDataZawieszeniaDzialalnosci;
        @XmlElement(name = "lokfiz_dataWznowieniaDzialalnosci")
        protected String lokfizDataWznowieniaDzialalnosci;
        @XmlElement(name = "lokfiz_dataZaistnieniaZmiany")
        protected String lokfizDataZaistnieniaZmiany;
        @XmlElement(name = "lokfiz_dataZakonczeniaDzialalnosci")
        protected String lokfizDataZakonczeniaDzialalnosci;
        @XmlElement(name = "lokfiz_dataSkresleniaZRegon")
        protected String lokfizDataSkresleniaZRegon;
        @XmlElement(name = "lokfiz_adSiedzKraj_Symbol")
        protected String lokfizAdSiedzKrajSymbol;
        @XmlElement(name = "lokfiz_adSiedzWojewodztwo_Symbol")
        protected String lokfizAdSiedzWojewodztwoSymbol;
        @XmlElement(name = "lokfiz_adSiedzPowiat_Symbol")
        protected String lokfizAdSiedzPowiatSymbol;
        @XmlElement(name = "lokfiz_adSiedzGmina_Symbol")
        protected String lokfizAdSiedzGminaSymbol;
        @XmlElement(name = "lokfiz_adSiedzKodPocztowy")
        protected String lokfizAdSiedzKodPocztowy;
        @XmlElement(name = "lokfiz_adSiedzMiejscowoscPoczty_Symbol")
        protected String lokfizAdSiedzMiejscowoscPocztySymbol;
        @XmlElement(name = "lokfiz_adSiedzMiejscowosc_Symbol")
        protected String lokfizAdSiedzMiejscowoscSymbol;
        @XmlElement(name = "lokfiz_adSiedzUlica_Symbol")
        protected String lokfizAdSiedzUlicaSymbol;
        @XmlElement(name = "lokfiz_adSiedzNumerNieruchomosci")
        protected String lokfizAdSiedzNumerNieruchomosci;
        @XmlElement(name = "lokfiz_adSiedzNumerLokalu")
        protected String lokfizAdSiedzNumerLokalu;
        @XmlElement(name = "lokfiz_adSiedzNietypoweMiejsceLokalizacji")
        protected String lokfizAdSiedzNietypoweMiejsceLokalizacji;
        @XmlElement(name = "lokfiz_adSiedzKraj_Nazwa")
        protected String lokfizAdSiedzKrajNazwa;
        @XmlElement(name = "lokfiz_adSiedzWojewodztwo_Nazwa")
        protected String lokfizAdSiedzWojewodztwoNazwa;
        @XmlElement(name = "lokfiz_adSiedzPowiat_Nazwa")
        protected String lokfizAdSiedzPowiatNazwa;
        @XmlElement(name = "lokfiz_adSiedzGmina_Nazwa")
        protected String lokfizAdSiedzGminaNazwa;
        @XmlElement(name = "lokfiz_adSiedzMiejscowosc_Nazwa")
        protected String lokfizAdSiedzMiejscowoscNazwa;
        @XmlElement(name = "lokfiz_adSiedzMiejscowoscPoczty_Nazwa")
        protected String lokfizAdSiedzMiejscowoscPocztyNazwa;
        @XmlElement(name = "lokfiz_adSiedzUlica_Nazwa")
        protected String lokfizAdSiedzUlicaNazwa;
        @XmlElement(name = "lokfiz_FormaFinansowania_Nazwa")
        protected String lokfizFormaFinansowaniaNazwa;
        @XmlElement(name = "lokfiz_FormaFinansowania_Symbol")
        protected String lokfizFormaFinansowaniaSymbol;
        @XmlElement(name = "lokfiz_dataWpisuDoRejestruEwidencji")
        protected String lokfizDataWpisuDoRejestruEwidencji;
        @XmlElement(name = "lokfiz_numerwRejestrzeEwidencji")
        protected String lokfizNumerwRejestrzeEwidencji;
        @XmlElement(name = "lokfiz_OrganRejestrowy_Symbol")
        protected String lokfizOrganRejestrowySymbol;
        @XmlElement(name = "lokfiz_RodzajRejestru_Symbol")
        protected String lokfizRodzajRejestruSymbol;
        @XmlElement(name = "lokfiz_OrganRejestrowy_Nazwa")
        protected String lokfizOrganRejestrowyNazwa;
        @XmlElement(name = "lokfiz_RodzajRejestru_Nazwa")
        protected String lokfizRodzajRejestruNazwa;
        @XmlElement(name = "lokfizC_NiePodjetoDzialalnosci")
        protected Boolean lokfizCNiePodjetoDzialalnosci;

        /**
         * Gets the value of the lokfizRegon14 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizRegon14() {
            return lokfizRegon14;
        }

        /**
         * Sets the value of the lokfizRegon14 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizRegon14(String value) {
            this.lokfizRegon14 = value;
        }

        /**
         * Gets the value of the lokfizNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizNazwa() {
            return lokfizNazwa;
        }

        /**
         * Sets the value of the lokfizNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizNazwa(String value) {
            this.lokfizNazwa = value;
        }

        /**
         * Gets the value of the lokfizSilosID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLokfizSilosID() {
            return lokfizSilosID;
        }

        /**
         * Sets the value of the lokfizSilosID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLokfizSilosID(Integer value) {
            this.lokfizSilosID = value;
        }

        /**
         * Gets the value of the lokfizSilosNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizSilosNazwa() {
            return lokfizSilosNazwa;
        }

        /**
         * Sets the value of the lokfizSilosNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizSilosNazwa(String value) {
            this.lokfizSilosNazwa = value;
        }

        /**
         * Gets the value of the lokfizDataPowstania property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizDataPowstania() {
            return lokfizDataPowstania;
        }

        /**
         * Sets the value of the lokfizDataPowstania property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizDataPowstania(String value) {
            this.lokfizDataPowstania = value;
        }

        /**
         * Gets the value of the lokfizDataRozpoczeciaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizDataRozpoczeciaDzialalnosci() {
            return lokfizDataRozpoczeciaDzialalnosci;
        }

        /**
         * Sets the value of the lokfizDataRozpoczeciaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizDataRozpoczeciaDzialalnosci(String value) {
            this.lokfizDataRozpoczeciaDzialalnosci = value;
        }

        /**
         * Gets the value of the lokfizDataWpisuDoRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizDataWpisuDoRegon() {
            return lokfizDataWpisuDoRegon;
        }

        /**
         * Sets the value of the lokfizDataWpisuDoRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizDataWpisuDoRegon(String value) {
            this.lokfizDataWpisuDoRegon = value;
        }

        /**
         * Gets the value of the lokfizDataZawieszeniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizDataZawieszeniaDzialalnosci() {
            return lokfizDataZawieszeniaDzialalnosci;
        }

        /**
         * Sets the value of the lokfizDataZawieszeniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizDataZawieszeniaDzialalnosci(String value) {
            this.lokfizDataZawieszeniaDzialalnosci = value;
        }

        /**
         * Gets the value of the lokfizDataWznowieniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizDataWznowieniaDzialalnosci() {
            return lokfizDataWznowieniaDzialalnosci;
        }

        /**
         * Sets the value of the lokfizDataWznowieniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizDataWznowieniaDzialalnosci(String value) {
            this.lokfizDataWznowieniaDzialalnosci = value;
        }

        /**
         * Gets the value of the lokfizDataZaistnieniaZmiany property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizDataZaistnieniaZmiany() {
            return lokfizDataZaistnieniaZmiany;
        }

        /**
         * Sets the value of the lokfizDataZaistnieniaZmiany property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizDataZaistnieniaZmiany(String value) {
            this.lokfizDataZaistnieniaZmiany = value;
        }

        /**
         * Gets the value of the lokfizDataZakonczeniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizDataZakonczeniaDzialalnosci() {
            return lokfizDataZakonczeniaDzialalnosci;
        }

        /**
         * Sets the value of the lokfizDataZakonczeniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizDataZakonczeniaDzialalnosci(String value) {
            this.lokfizDataZakonczeniaDzialalnosci = value;
        }

        /**
         * Gets the value of the lokfizDataSkresleniaZRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizDataSkresleniaZRegon() {
            return lokfizDataSkresleniaZRegon;
        }

        /**
         * Sets the value of the lokfizDataSkresleniaZRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizDataSkresleniaZRegon(String value) {
            this.lokfizDataSkresleniaZRegon = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzKrajSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzKrajSymbol() {
            return lokfizAdSiedzKrajSymbol;
        }

        /**
         * Sets the value of the lokfizAdSiedzKrajSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzKrajSymbol(String value) {
            this.lokfizAdSiedzKrajSymbol = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzWojewodztwoSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzWojewodztwoSymbol() {
            return lokfizAdSiedzWojewodztwoSymbol;
        }

        /**
         * Sets the value of the lokfizAdSiedzWojewodztwoSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzWojewodztwoSymbol(String value) {
            this.lokfizAdSiedzWojewodztwoSymbol = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzPowiatSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzPowiatSymbol() {
            return lokfizAdSiedzPowiatSymbol;
        }

        /**
         * Sets the value of the lokfizAdSiedzPowiatSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzPowiatSymbol(String value) {
            this.lokfizAdSiedzPowiatSymbol = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzGminaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzGminaSymbol() {
            return lokfizAdSiedzGminaSymbol;
        }

        /**
         * Sets the value of the lokfizAdSiedzGminaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzGminaSymbol(String value) {
            this.lokfizAdSiedzGminaSymbol = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzKodPocztowy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzKodPocztowy() {
            return lokfizAdSiedzKodPocztowy;
        }

        /**
         * Sets the value of the lokfizAdSiedzKodPocztowy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzKodPocztowy(String value) {
            this.lokfizAdSiedzKodPocztowy = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzMiejscowoscPocztySymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzMiejscowoscPocztySymbol() {
            return lokfizAdSiedzMiejscowoscPocztySymbol;
        }

        /**
         * Sets the value of the lokfizAdSiedzMiejscowoscPocztySymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzMiejscowoscPocztySymbol(String value) {
            this.lokfizAdSiedzMiejscowoscPocztySymbol = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzMiejscowoscSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzMiejscowoscSymbol() {
            return lokfizAdSiedzMiejscowoscSymbol;
        }

        /**
         * Sets the value of the lokfizAdSiedzMiejscowoscSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzMiejscowoscSymbol(String value) {
            this.lokfizAdSiedzMiejscowoscSymbol = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzUlicaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzUlicaSymbol() {
            return lokfizAdSiedzUlicaSymbol;
        }

        /**
         * Sets the value of the lokfizAdSiedzUlicaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzUlicaSymbol(String value) {
            this.lokfizAdSiedzUlicaSymbol = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzNumerNieruchomosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzNumerNieruchomosci() {
            return lokfizAdSiedzNumerNieruchomosci;
        }

        /**
         * Sets the value of the lokfizAdSiedzNumerNieruchomosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzNumerNieruchomosci(String value) {
            this.lokfizAdSiedzNumerNieruchomosci = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzNumerLokalu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzNumerLokalu() {
            return lokfizAdSiedzNumerLokalu;
        }

        /**
         * Sets the value of the lokfizAdSiedzNumerLokalu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzNumerLokalu(String value) {
            this.lokfizAdSiedzNumerLokalu = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzNietypoweMiejsceLokalizacji property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzNietypoweMiejsceLokalizacji() {
            return lokfizAdSiedzNietypoweMiejsceLokalizacji;
        }

        /**
         * Sets the value of the lokfizAdSiedzNietypoweMiejsceLokalizacji property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzNietypoweMiejsceLokalizacji(String value) {
            this.lokfizAdSiedzNietypoweMiejsceLokalizacji = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzKrajNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzKrajNazwa() {
            return lokfizAdSiedzKrajNazwa;
        }

        /**
         * Sets the value of the lokfizAdSiedzKrajNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzKrajNazwa(String value) {
            this.lokfizAdSiedzKrajNazwa = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzWojewodztwoNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzWojewodztwoNazwa() {
            return lokfizAdSiedzWojewodztwoNazwa;
        }

        /**
         * Sets the value of the lokfizAdSiedzWojewodztwoNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzWojewodztwoNazwa(String value) {
            this.lokfizAdSiedzWojewodztwoNazwa = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzPowiatNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzPowiatNazwa() {
            return lokfizAdSiedzPowiatNazwa;
        }

        /**
         * Sets the value of the lokfizAdSiedzPowiatNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzPowiatNazwa(String value) {
            this.lokfizAdSiedzPowiatNazwa = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzGminaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzGminaNazwa() {
            return lokfizAdSiedzGminaNazwa;
        }

        /**
         * Sets the value of the lokfizAdSiedzGminaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzGminaNazwa(String value) {
            this.lokfizAdSiedzGminaNazwa = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzMiejscowoscNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzMiejscowoscNazwa() {
            return lokfizAdSiedzMiejscowoscNazwa;
        }

        /**
         * Sets the value of the lokfizAdSiedzMiejscowoscNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzMiejscowoscNazwa(String value) {
            this.lokfizAdSiedzMiejscowoscNazwa = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzMiejscowoscPocztyNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzMiejscowoscPocztyNazwa() {
            return lokfizAdSiedzMiejscowoscPocztyNazwa;
        }

        /**
         * Sets the value of the lokfizAdSiedzMiejscowoscPocztyNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzMiejscowoscPocztyNazwa(String value) {
            this.lokfizAdSiedzMiejscowoscPocztyNazwa = value;
        }

        /**
         * Gets the value of the lokfizAdSiedzUlicaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizAdSiedzUlicaNazwa() {
            return lokfizAdSiedzUlicaNazwa;
        }

        /**
         * Sets the value of the lokfizAdSiedzUlicaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizAdSiedzUlicaNazwa(String value) {
            this.lokfizAdSiedzUlicaNazwa = value;
        }

        /**
         * Gets the value of the lokfizFormaFinansowaniaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizFormaFinansowaniaNazwa() {
            return lokfizFormaFinansowaniaNazwa;
        }

        /**
         * Sets the value of the lokfizFormaFinansowaniaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizFormaFinansowaniaNazwa(String value) {
            this.lokfizFormaFinansowaniaNazwa = value;
        }

        /**
         * Gets the value of the lokfizFormaFinansowaniaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizFormaFinansowaniaSymbol() {
            return lokfizFormaFinansowaniaSymbol;
        }

        /**
         * Sets the value of the lokfizFormaFinansowaniaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizFormaFinansowaniaSymbol(String value) {
            this.lokfizFormaFinansowaniaSymbol = value;
        }

        /**
         * Gets the value of the lokfizDataWpisuDoRejestruEwidencji property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizDataWpisuDoRejestruEwidencji() {
            return lokfizDataWpisuDoRejestruEwidencji;
        }

        /**
         * Sets the value of the lokfizDataWpisuDoRejestruEwidencji property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizDataWpisuDoRejestruEwidencji(String value) {
            this.lokfizDataWpisuDoRejestruEwidencji = value;
        }

        /**
         * Gets the value of the lokfizNumerwRejestrzeEwidencji property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizNumerwRejestrzeEwidencji() {
            return lokfizNumerwRejestrzeEwidencji;
        }

        /**
         * Sets the value of the lokfizNumerwRejestrzeEwidencji property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizNumerwRejestrzeEwidencji(String value) {
            this.lokfizNumerwRejestrzeEwidencji = value;
        }

        /**
         * Gets the value of the lokfizOrganRejestrowySymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizOrganRejestrowySymbol() {
            return lokfizOrganRejestrowySymbol;
        }

        /**
         * Sets the value of the lokfizOrganRejestrowySymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizOrganRejestrowySymbol(String value) {
            this.lokfizOrganRejestrowySymbol = value;
        }

        /**
         * Gets the value of the lokfizRodzajRejestruSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizRodzajRejestruSymbol() {
            return lokfizRodzajRejestruSymbol;
        }

        /**
         * Sets the value of the lokfizRodzajRejestruSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizRodzajRejestruSymbol(String value) {
            this.lokfizRodzajRejestruSymbol = value;
        }

        /**
         * Gets the value of the lokfizOrganRejestrowyNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizOrganRejestrowyNazwa() {
            return lokfizOrganRejestrowyNazwa;
        }

        /**
         * Sets the value of the lokfizOrganRejestrowyNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizOrganRejestrowyNazwa(String value) {
            this.lokfizOrganRejestrowyNazwa = value;
        }

        /**
         * Gets the value of the lokfizRodzajRejestruNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizRodzajRejestruNazwa() {
            return lokfizRodzajRejestruNazwa;
        }

        /**
         * Sets the value of the lokfizRodzajRejestruNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizRodzajRejestruNazwa(String value) {
            this.lokfizRodzajRejestruNazwa = value;
        }

        /**
         * Gets the value of the lokfizCNiePodjetoDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isLokfizCNiePodjetoDzialalnosci() {
            return lokfizCNiePodjetoDzialalnosci;
        }

        /**
         * Sets the value of the lokfizCNiePodjetoDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLokfizCNiePodjetoDzialalnosci(Boolean value) {
            this.lokfizCNiePodjetoDzialalnosci = value;
        }

    }

}
