//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 06:33:16 PM CET 
//


package com.archu.gussoapintegration.integration.regon.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dane" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="fiz_pkd_Kod" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="5"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_pkd_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_pkd_Przewazajace" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_SilosID" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_Silos_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataSkresleniaDzialalnosciZRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dane"
})
@XmlRootElement(name = "root")
public class OsFizycznaPkdRoot {

    protected List<OsFizycznaPkdData> dane;

    /**
     * Gets the value of the dane property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dane property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDane().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OsFizycznaPkdData }
     * 
     * 
     */
    public List<OsFizycznaPkdData> getDane() {
        if (dane == null) {
            dane = new ArrayList<OsFizycznaPkdData>();
        }
        return this.dane;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="fiz_pkd_Kod" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="5"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_pkd_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_pkd_Przewazajace" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_SilosID" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_Silos_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataSkresleniaDzialalnosciZRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fizPkdKod",
        "fizPkdNazwa",
        "fizPkdPrzewazajace",
        "fizSilosID",
        "fizSilosSymbol",
        "fizDataSkresleniaDzialalnosciZRegon"
    })
    public static class OsFizycznaPkdData {

        @XmlElement(name = "fiz_pkd_Kod")
        protected String fizPkdKod;
        @XmlElement(name = "fiz_pkd_Nazwa")
        protected String fizPkdNazwa;
        @XmlElement(name = "fiz_pkd_Przewazajace")
        protected String fizPkdPrzewazajace;
        @XmlElement(name = "fiz_SilosID")
        protected Integer fizSilosID;
        @XmlElement(name = "fiz_Silos_Symbol")
        protected String fizSilosSymbol;
        @XmlElement(name = "fiz_dataSkresleniaDzialalnosciZRegon")
        protected String fizDataSkresleniaDzialalnosciZRegon;

        /**
         * Gets the value of the fizPkdKod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizPkdKod() {
            return fizPkdKod;
        }

        /**
         * Sets the value of the fizPkdKod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizPkdKod(String value) {
            this.fizPkdKod = value;
        }

        /**
         * Gets the value of the fizPkdNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizPkdNazwa() {
            return fizPkdNazwa;
        }

        /**
         * Sets the value of the fizPkdNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizPkdNazwa(String value) {
            this.fizPkdNazwa = value;
        }

        /**
         * Gets the value of the fizPkdPrzewazajace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizPkdPrzewazajace() {
            return fizPkdPrzewazajace;
        }

        /**
         * Sets the value of the fizPkdPrzewazajace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizPkdPrzewazajace(String value) {
            this.fizPkdPrzewazajace = value;
        }

        /**
         * Gets the value of the fizSilosID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFizSilosID() {
            return fizSilosID;
        }

        /**
         * Sets the value of the fizSilosID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFizSilosID(Integer value) {
            this.fizSilosID = value;
        }

        /**
         * Gets the value of the fizSilosSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizSilosSymbol() {
            return fizSilosSymbol;
        }

        /**
         * Sets the value of the fizSilosSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizSilosSymbol(String value) {
            this.fizSilosSymbol = value;
        }

        /**
         * Gets the value of the fizDataSkresleniaDzialalnosciZRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataSkresleniaDzialalnosciZRegon() {
            return fizDataSkresleniaDzialalnosciZRegon;
        }

        /**
         * Sets the value of the fizDataSkresleniaDzialalnosciZRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataSkresleniaDzialalnosciZRegon(String value) {
            this.fizDataSkresleniaDzialalnosciZRegon = value;
        }

    }

}
