//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.23 at 06:19:26 PM CET 
//


package com.archu.gussoapintegration.integration.regon.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dane" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="lokpraw_regon14" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="14"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="254"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzKraj_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzWojewodztwo_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzPowiat_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzGmina_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzKodPocztowy" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="12"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzMiejscowoscPoczty_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="7"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzMiejscowosc_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="7"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzUlica_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="5"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzNumerNieruchomosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="20"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzNumerLokalu" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzNietypoweMiejsceLokalizacji" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="160"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzWojewodztwo_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzPowiat_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzGmina_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzMiejscowosc_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzMiejscowoscPoczty_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_adSiedzUlica_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="351"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_dataPowstania" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_dataRozpoczeciaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_dataWpisuDoRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_dataZawieszeniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_dataWznowieniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_dataZakonczeniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokpraw_dataSkresleniaZRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dane"
})
@XmlRootElement(name = "root")
public class OsPrawnaListaJednLokalnychRoot {

    protected List<OsPrawnaListaJednLokalnychData> dane;

    /**
     * Gets the value of the dane property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dane property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDane().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OsPrawnaListaJednLokalnychData }
     * 
     * 
     */
    public List<OsPrawnaListaJednLokalnychData> getDane() {
        if (dane == null) {
            dane = new ArrayList<OsPrawnaListaJednLokalnychData>();
        }
        return this.dane;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lokpraw_regon14" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="14"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="254"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzKraj_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzWojewodztwo_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzPowiat_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzGmina_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzKodPocztowy" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="12"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzMiejscowoscPoczty_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="7"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzMiejscowosc_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="7"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzUlica_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="5"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzNumerNieruchomosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="20"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzNumerLokalu" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzNietypoweMiejsceLokalizacji" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="160"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzWojewodztwo_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzPowiat_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzGmina_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzMiejscowosc_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzMiejscowoscPoczty_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_adSiedzUlica_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="351"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_dataPowstania" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_dataRozpoczeciaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_dataWpisuDoRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_dataZawieszeniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_dataWznowieniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_dataZakonczeniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokpraw_dataSkresleniaZRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lokprawRegon14",
        "lokprawNazwa",
        "lokprawAdSiedzKrajSymbol",
        "lokprawAdSiedzWojewodztwoSymbol",
        "lokprawAdSiedzPowiatSymbol",
        "lokprawAdSiedzGminaSymbol",
        "lokprawAdSiedzKodPocztowy",
        "lokprawAdSiedzMiejscowoscPocztySymbol",
        "lokprawAdSiedzMiejscowoscSymbol",
        "lokprawAdSiedzUlicaSymbol",
        "lokprawAdSiedzNumerNieruchomosci",
        "lokprawAdSiedzNumerLokalu",
        "lokprawAdSiedzNietypoweMiejsceLokalizacji",
        "lokprawAdSiedzWojewodztwoNazwa",
        "lokprawAdSiedzPowiatNazwa",
        "lokprawAdSiedzGminaNazwa",
        "lokprawAdSiedzMiejscowoscNazwa",
        "lokprawAdSiedzMiejscowoscPocztyNazwa",
        "lokprawAdSiedzUlicaNazwa",
        "lokprawDataPowstania",
        "lokprawDataRozpoczeciaDzialalnosci",
        "lokprawDataWpisuDoRegon",
        "lokprawDataZawieszeniaDzialalnosci",
        "lokprawDataWznowieniaDzialalnosci",
        "lokprawDataZakonczeniaDzialalnosci",
        "lokprawDataSkresleniaZRegon"
    })
    public static class OsPrawnaListaJednLokalnychData {

        @XmlElement(name = "lokpraw_regon14")
        protected String lokprawRegon14;
        @XmlElement(name = "lokpraw_nazwa")
        protected String lokprawNazwa;
        @XmlElement(name = "lokpraw_adSiedzKraj_Symbol")
        protected String lokprawAdSiedzKrajSymbol;
        @XmlElement(name = "lokpraw_adSiedzWojewodztwo_Symbol")
        protected String lokprawAdSiedzWojewodztwoSymbol;
        @XmlElement(name = "lokpraw_adSiedzPowiat_Symbol")
        protected String lokprawAdSiedzPowiatSymbol;
        @XmlElement(name = "lokpraw_adSiedzGmina_Symbol")
        protected String lokprawAdSiedzGminaSymbol;
        @XmlElement(name = "lokpraw_adSiedzKodPocztowy")
        protected String lokprawAdSiedzKodPocztowy;
        @XmlElement(name = "lokpraw_adSiedzMiejscowoscPoczty_Symbol")
        protected String lokprawAdSiedzMiejscowoscPocztySymbol;
        @XmlElement(name = "lokpraw_adSiedzMiejscowosc_Symbol")
        protected String lokprawAdSiedzMiejscowoscSymbol;
        @XmlElement(name = "lokpraw_adSiedzUlica_Symbol")
        protected String lokprawAdSiedzUlicaSymbol;
        @XmlElement(name = "lokpraw_adSiedzNumerNieruchomosci")
        protected String lokprawAdSiedzNumerNieruchomosci;
        @XmlElement(name = "lokpraw_adSiedzNumerLokalu")
        protected String lokprawAdSiedzNumerLokalu;
        @XmlElement(name = "lokpraw_adSiedzNietypoweMiejsceLokalizacji")
        protected String lokprawAdSiedzNietypoweMiejsceLokalizacji;
        @XmlElement(name = "lokpraw_adSiedzWojewodztwo_Nazwa")
        protected String lokprawAdSiedzWojewodztwoNazwa;
        @XmlElement(name = "lokpraw_adSiedzPowiat_Nazwa")
        protected String lokprawAdSiedzPowiatNazwa;
        @XmlElement(name = "lokpraw_adSiedzGmina_Nazwa")
        protected String lokprawAdSiedzGminaNazwa;
        @XmlElement(name = "lokpraw_adSiedzMiejscowosc_Nazwa")
        protected String lokprawAdSiedzMiejscowoscNazwa;
        @XmlElement(name = "lokpraw_adSiedzMiejscowoscPoczty_Nazwa")
        protected String lokprawAdSiedzMiejscowoscPocztyNazwa;
        @XmlElement(name = "lokpraw_adSiedzUlica_Nazwa")
        protected String lokprawAdSiedzUlicaNazwa;
        @XmlElement(name = "lokpraw_dataPowstania")
        protected String lokprawDataPowstania;
        @XmlElement(name = "lokpraw_dataRozpoczeciaDzialalnosci")
        protected String lokprawDataRozpoczeciaDzialalnosci;
        @XmlElement(name = "lokpraw_dataWpisuDoRegon")
        protected String lokprawDataWpisuDoRegon;
        @XmlElement(name = "lokpraw_dataZawieszeniaDzialalnosci")
        protected String lokprawDataZawieszeniaDzialalnosci;
        @XmlElement(name = "lokpraw_dataWznowieniaDzialalnosci")
        protected String lokprawDataWznowieniaDzialalnosci;
        @XmlElement(name = "lokpraw_dataZakonczeniaDzialalnosci")
        protected String lokprawDataZakonczeniaDzialalnosci;
        @XmlElement(name = "lokpraw_dataSkresleniaZRegon")
        protected String lokprawDataSkresleniaZRegon;

        /**
         * Gets the value of the lokprawRegon14 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawRegon14() {
            return lokprawRegon14;
        }

        /**
         * Sets the value of the lokprawRegon14 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawRegon14(String value) {
            this.lokprawRegon14 = value;
        }

        /**
         * Gets the value of the lokprawNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawNazwa() {
            return lokprawNazwa;
        }

        /**
         * Sets the value of the lokprawNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawNazwa(String value) {
            this.lokprawNazwa = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzKrajSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzKrajSymbol() {
            return lokprawAdSiedzKrajSymbol;
        }

        /**
         * Sets the value of the lokprawAdSiedzKrajSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzKrajSymbol(String value) {
            this.lokprawAdSiedzKrajSymbol = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzWojewodztwoSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzWojewodztwoSymbol() {
            return lokprawAdSiedzWojewodztwoSymbol;
        }

        /**
         * Sets the value of the lokprawAdSiedzWojewodztwoSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzWojewodztwoSymbol(String value) {
            this.lokprawAdSiedzWojewodztwoSymbol = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzPowiatSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzPowiatSymbol() {
            return lokprawAdSiedzPowiatSymbol;
        }

        /**
         * Sets the value of the lokprawAdSiedzPowiatSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzPowiatSymbol(String value) {
            this.lokprawAdSiedzPowiatSymbol = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzGminaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzGminaSymbol() {
            return lokprawAdSiedzGminaSymbol;
        }

        /**
         * Sets the value of the lokprawAdSiedzGminaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzGminaSymbol(String value) {
            this.lokprawAdSiedzGminaSymbol = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzKodPocztowy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzKodPocztowy() {
            return lokprawAdSiedzKodPocztowy;
        }

        /**
         * Sets the value of the lokprawAdSiedzKodPocztowy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzKodPocztowy(String value) {
            this.lokprawAdSiedzKodPocztowy = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzMiejscowoscPocztySymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzMiejscowoscPocztySymbol() {
            return lokprawAdSiedzMiejscowoscPocztySymbol;
        }

        /**
         * Sets the value of the lokprawAdSiedzMiejscowoscPocztySymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzMiejscowoscPocztySymbol(String value) {
            this.lokprawAdSiedzMiejscowoscPocztySymbol = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzMiejscowoscSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzMiejscowoscSymbol() {
            return lokprawAdSiedzMiejscowoscSymbol;
        }

        /**
         * Sets the value of the lokprawAdSiedzMiejscowoscSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzMiejscowoscSymbol(String value) {
            this.lokprawAdSiedzMiejscowoscSymbol = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzUlicaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzUlicaSymbol() {
            return lokprawAdSiedzUlicaSymbol;
        }

        /**
         * Sets the value of the lokprawAdSiedzUlicaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzUlicaSymbol(String value) {
            this.lokprawAdSiedzUlicaSymbol = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzNumerNieruchomosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzNumerNieruchomosci() {
            return lokprawAdSiedzNumerNieruchomosci;
        }

        /**
         * Sets the value of the lokprawAdSiedzNumerNieruchomosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzNumerNieruchomosci(String value) {
            this.lokprawAdSiedzNumerNieruchomosci = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzNumerLokalu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzNumerLokalu() {
            return lokprawAdSiedzNumerLokalu;
        }

        /**
         * Sets the value of the lokprawAdSiedzNumerLokalu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzNumerLokalu(String value) {
            this.lokprawAdSiedzNumerLokalu = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzNietypoweMiejsceLokalizacji property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzNietypoweMiejsceLokalizacji() {
            return lokprawAdSiedzNietypoweMiejsceLokalizacji;
        }

        /**
         * Sets the value of the lokprawAdSiedzNietypoweMiejsceLokalizacji property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzNietypoweMiejsceLokalizacji(String value) {
            this.lokprawAdSiedzNietypoweMiejsceLokalizacji = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzWojewodztwoNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzWojewodztwoNazwa() {
            return lokprawAdSiedzWojewodztwoNazwa;
        }

        /**
         * Sets the value of the lokprawAdSiedzWojewodztwoNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzWojewodztwoNazwa(String value) {
            this.lokprawAdSiedzWojewodztwoNazwa = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzPowiatNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzPowiatNazwa() {
            return lokprawAdSiedzPowiatNazwa;
        }

        /**
         * Sets the value of the lokprawAdSiedzPowiatNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzPowiatNazwa(String value) {
            this.lokprawAdSiedzPowiatNazwa = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzGminaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzGminaNazwa() {
            return lokprawAdSiedzGminaNazwa;
        }

        /**
         * Sets the value of the lokprawAdSiedzGminaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzGminaNazwa(String value) {
            this.lokprawAdSiedzGminaNazwa = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzMiejscowoscNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzMiejscowoscNazwa() {
            return lokprawAdSiedzMiejscowoscNazwa;
        }

        /**
         * Sets the value of the lokprawAdSiedzMiejscowoscNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzMiejscowoscNazwa(String value) {
            this.lokprawAdSiedzMiejscowoscNazwa = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzMiejscowoscPocztyNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzMiejscowoscPocztyNazwa() {
            return lokprawAdSiedzMiejscowoscPocztyNazwa;
        }

        /**
         * Sets the value of the lokprawAdSiedzMiejscowoscPocztyNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzMiejscowoscPocztyNazwa(String value) {
            this.lokprawAdSiedzMiejscowoscPocztyNazwa = value;
        }

        /**
         * Gets the value of the lokprawAdSiedzUlicaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawAdSiedzUlicaNazwa() {
            return lokprawAdSiedzUlicaNazwa;
        }

        /**
         * Sets the value of the lokprawAdSiedzUlicaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawAdSiedzUlicaNazwa(String value) {
            this.lokprawAdSiedzUlicaNazwa = value;
        }

        /**
         * Gets the value of the lokprawDataPowstania property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawDataPowstania() {
            return lokprawDataPowstania;
        }

        /**
         * Sets the value of the lokprawDataPowstania property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawDataPowstania(String value) {
            this.lokprawDataPowstania = value;
        }

        /**
         * Gets the value of the lokprawDataRozpoczeciaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawDataRozpoczeciaDzialalnosci() {
            return lokprawDataRozpoczeciaDzialalnosci;
        }

        /**
         * Sets the value of the lokprawDataRozpoczeciaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawDataRozpoczeciaDzialalnosci(String value) {
            this.lokprawDataRozpoczeciaDzialalnosci = value;
        }

        /**
         * Gets the value of the lokprawDataWpisuDoRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawDataWpisuDoRegon() {
            return lokprawDataWpisuDoRegon;
        }

        /**
         * Sets the value of the lokprawDataWpisuDoRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawDataWpisuDoRegon(String value) {
            this.lokprawDataWpisuDoRegon = value;
        }

        /**
         * Gets the value of the lokprawDataZawieszeniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawDataZawieszeniaDzialalnosci() {
            return lokprawDataZawieszeniaDzialalnosci;
        }

        /**
         * Sets the value of the lokprawDataZawieszeniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawDataZawieszeniaDzialalnosci(String value) {
            this.lokprawDataZawieszeniaDzialalnosci = value;
        }

        /**
         * Gets the value of the lokprawDataWznowieniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawDataWznowieniaDzialalnosci() {
            return lokprawDataWznowieniaDzialalnosci;
        }

        /**
         * Sets the value of the lokprawDataWznowieniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawDataWznowieniaDzialalnosci(String value) {
            this.lokprawDataWznowieniaDzialalnosci = value;
        }

        /**
         * Gets the value of the lokprawDataZakonczeniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawDataZakonczeniaDzialalnosci() {
            return lokprawDataZakonczeniaDzialalnosci;
        }

        /**
         * Sets the value of the lokprawDataZakonczeniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawDataZakonczeniaDzialalnosci(String value) {
            this.lokprawDataZakonczeniaDzialalnosci = value;
        }

        /**
         * Gets the value of the lokprawDataSkresleniaZRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokprawDataSkresleniaZRegon() {
            return lokprawDataSkresleniaZRegon;
        }

        /**
         * Sets the value of the lokprawDataSkresleniaZRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokprawDataSkresleniaZRegon(String value) {
            this.lokprawDataSkresleniaZRegon = value;
        }

    }

}
