//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.23 at 06:18:13 PM CET 
//


package com.archu.gussoapintegration.integration.regon.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dane"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="praw_regon9" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="9"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_nip" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_statusNip" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value=""/&gt;
 *                         &lt;enumeration value="Uchylony"/&gt;
 *                         &lt;enumeration value="Unieważniony"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2000"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_nazwaSkrocona" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="256"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_numerWRejestrzeEwidencji" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="50"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataWpisuDoRejestruEwidencji" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataPowstania" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataRozpoczeciaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataWpisuDoRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataZawieszeniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataWznowieniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataZaistnieniaZmiany" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataZakonczeniaDzialalnosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataSkresleniaZRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataOrzeczeniaOUpadlosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_dataZakonczeniaPostepowaniaUpadlosciowego" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzKraj_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzWojewodztwo_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzPowiat_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzGmina_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzKodPocztowy" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="12"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzMiejscowoscPoczty_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="7"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzMiejscowosc_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="7"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzUlica_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="5"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzNumerNieruchomosci" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="20"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzNumerLokalu" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzNietypoweMiejsceLokalizacji" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="160"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_numerTelefonu" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="18"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_numerWewnetrznyTelefonu" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="6"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_numerFaksu" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="18"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adresEmail" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adresStronyinternetowej" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzKraj_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzWojewodztwo_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzPowiat_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzGmina_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzMiejscowosc_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzMiejscowoscPoczty_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_adSiedzUlica_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="351"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_podstawowaFormaPrawna_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_szczegolnaFormaPrawna_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_formaFinansowania_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_formaWlasnosci_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="50"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_organZalozycielski_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="9"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_organRejestrowy_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="9"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_rodzajRejestruEwidencji_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_podstawowaFormaPrawna_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_szczegolnaFormaPrawna_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_formaFinansowania_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="240"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_formaWlasnosci_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="240"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_organZalozycielski_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_organRejestrowy_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="240"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_rodzajRejestruEwidencji_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="240"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="praw_liczbaJednLokalnych" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dane"
})
@XmlRootElement(name = "root")
public class OsPrawnaRoot {

    @XmlElement(required = true)
    protected OsPrawnaData dane;

    /**
     * Gets the value of the dane property.
     * 
     * @return
     *     possible object is
     *     {@link OsPrawnaData }
     *     
     */
    public OsPrawnaData getDane() {
        return dane;
    }

    /**
     * Sets the value of the dane property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsPrawnaData }
     *     
     */
    public void setDane(OsPrawnaData value) {
        this.dane = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="praw_regon9" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="9"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_nip" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_statusNip" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value=""/&gt;
     *               &lt;enumeration value="Uchylony"/&gt;
     *               &lt;enumeration value="Unieważniony"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2000"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_nazwaSkrocona" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="256"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_numerWRejestrzeEwidencji" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="50"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataWpisuDoRejestruEwidencji" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataPowstania" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataRozpoczeciaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataWpisuDoRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataZawieszeniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataWznowieniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataZaistnieniaZmiany" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataZakonczeniaDzialalnosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataSkresleniaZRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataOrzeczeniaOUpadlosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_dataZakonczeniaPostepowaniaUpadlosciowego" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzKraj_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzWojewodztwo_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzPowiat_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzGmina_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzKodPocztowy" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="12"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzMiejscowoscPoczty_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="7"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzMiejscowosc_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="7"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzUlica_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="5"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzNumerNieruchomosci" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="20"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzNumerLokalu" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzNietypoweMiejsceLokalizacji" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="160"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_numerTelefonu" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="18"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_numerWewnetrznyTelefonu" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="6"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_numerFaksu" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="18"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adresEmail" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adresStronyinternetowej" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzKraj_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzWojewodztwo_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzPowiat_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzGmina_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzMiejscowosc_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzMiejscowoscPoczty_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_adSiedzUlica_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="351"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_podstawowaFormaPrawna_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_szczegolnaFormaPrawna_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_formaFinansowania_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_formaWlasnosci_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="50"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_organZalozycielski_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="9"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_organRejestrowy_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="9"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_rodzajRejestruEwidencji_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_podstawowaFormaPrawna_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_szczegolnaFormaPrawna_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_formaFinansowania_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="240"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_formaWlasnosci_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="240"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_organZalozycielski_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_organRejestrowy_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="240"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_rodzajRejestruEwidencji_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="240"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="praw_liczbaJednLokalnych" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prawRegon9",
        "prawNip",
        "prawStatusNip",
        "prawNazwa",
        "prawNazwaSkrocona",
        "prawNumerWRejestrzeEwidencji",
        "prawDataWpisuDoRejestruEwidencji",
        "prawDataPowstania",
        "prawDataRozpoczeciaDzialalnosci",
        "prawDataWpisuDoRegon",
        "prawDataZawieszeniaDzialalnosci",
        "prawDataWznowieniaDzialalnosci",
        "prawDataZaistnieniaZmiany",
        "prawDataZakonczeniaDzialalnosci",
        "prawDataSkresleniaZRegon",
        "prawDataOrzeczeniaOUpadlosci",
        "prawDataZakonczeniaPostepowaniaUpadlosciowego",
        "prawAdSiedzKrajSymbol",
        "prawAdSiedzWojewodztwoSymbol",
        "prawAdSiedzPowiatSymbol",
        "prawAdSiedzGminaSymbol",
        "prawAdSiedzKodPocztowy",
        "prawAdSiedzMiejscowoscPocztySymbol",
        "prawAdSiedzMiejscowoscSymbol",
        "prawAdSiedzUlicaSymbol",
        "prawAdSiedzNumerNieruchomosci",
        "prawAdSiedzNumerLokalu",
        "prawAdSiedzNietypoweMiejsceLokalizacji",
        "prawNumerTelefonu",
        "prawNumerWewnetrznyTelefonu",
        "prawNumerFaksu",
        "prawAdresEmail",
        "prawAdresStronyinternetowej",
        "prawAdSiedzKrajNazwa",
        "prawAdSiedzWojewodztwoNazwa",
        "prawAdSiedzPowiatNazwa",
        "prawAdSiedzGminaNazwa",
        "prawAdSiedzMiejscowoscNazwa",
        "prawAdSiedzMiejscowoscPocztyNazwa",
        "prawAdSiedzUlicaNazwa",
        "prawPodstawowaFormaPrawnaSymbol",
        "prawSzczegolnaFormaPrawnaSymbol",
        "prawFormaFinansowaniaSymbol",
        "prawFormaWlasnosciSymbol",
        "prawOrganZalozycielskiSymbol",
        "prawOrganRejestrowySymbol",
        "prawRodzajRejestruEwidencjiSymbol",
        "prawPodstawowaFormaPrawnaNazwa",
        "prawSzczegolnaFormaPrawnaNazwa",
        "prawFormaFinansowaniaNazwa",
        "prawFormaWlasnosciNazwa",
        "prawOrganZalozycielskiNazwa",
        "prawOrganRejestrowyNazwa",
        "prawRodzajRejestruEwidencjiNazwa",
        "prawLiczbaJednLokalnych"
    })
    public static class OsPrawnaData {

        @XmlElement(name = "praw_regon9")
        protected String prawRegon9;
        @XmlElement(name = "praw_nip")
        protected String prawNip;
        @XmlElement(name = "praw_statusNip")
        protected String prawStatusNip;
        @XmlElement(name = "praw_nazwa")
        protected String prawNazwa;
        @XmlElement(name = "praw_nazwaSkrocona")
        protected String prawNazwaSkrocona;
        @XmlElement(name = "praw_numerWRejestrzeEwidencji")
        protected String prawNumerWRejestrzeEwidencji;
        @XmlElement(name = "praw_dataWpisuDoRejestruEwidencji")
        protected String prawDataWpisuDoRejestruEwidencji;
        @XmlElement(name = "praw_dataPowstania")
        protected String prawDataPowstania;
        @XmlElement(name = "praw_dataRozpoczeciaDzialalnosci")
        protected String prawDataRozpoczeciaDzialalnosci;
        @XmlElement(name = "praw_dataWpisuDoRegon")
        protected String prawDataWpisuDoRegon;
        @XmlElement(name = "praw_dataZawieszeniaDzialalnosci")
        protected String prawDataZawieszeniaDzialalnosci;
        @XmlElement(name = "praw_dataWznowieniaDzialalnosci")
        protected String prawDataWznowieniaDzialalnosci;
        @XmlElement(name = "praw_dataZaistnieniaZmiany")
        protected String prawDataZaistnieniaZmiany;
        @XmlElement(name = "praw_dataZakonczeniaDzialalnosci")
        protected String prawDataZakonczeniaDzialalnosci;
        @XmlElement(name = "praw_dataSkresleniaZRegon")
        protected String prawDataSkresleniaZRegon;
        @XmlElement(name = "praw_dataOrzeczeniaOUpadlosci")
        protected String prawDataOrzeczeniaOUpadlosci;
        @XmlElement(name = "praw_dataZakonczeniaPostepowaniaUpadlosciowego")
        protected String prawDataZakonczeniaPostepowaniaUpadlosciowego;
        @XmlElement(name = "praw_adSiedzKraj_Symbol")
        protected String prawAdSiedzKrajSymbol;
        @XmlElement(name = "praw_adSiedzWojewodztwo_Symbol")
        protected String prawAdSiedzWojewodztwoSymbol;
        @XmlElement(name = "praw_adSiedzPowiat_Symbol")
        protected String prawAdSiedzPowiatSymbol;
        @XmlElement(name = "praw_adSiedzGmina_Symbol")
        protected String prawAdSiedzGminaSymbol;
        @XmlElement(name = "praw_adSiedzKodPocztowy")
        protected String prawAdSiedzKodPocztowy;
        @XmlElement(name = "praw_adSiedzMiejscowoscPoczty_Symbol")
        protected String prawAdSiedzMiejscowoscPocztySymbol;
        @XmlElement(name = "praw_adSiedzMiejscowosc_Symbol")
        protected String prawAdSiedzMiejscowoscSymbol;
        @XmlElement(name = "praw_adSiedzUlica_Symbol")
        protected String prawAdSiedzUlicaSymbol;
        @XmlElement(name = "praw_adSiedzNumerNieruchomosci")
        protected String prawAdSiedzNumerNieruchomosci;
        @XmlElement(name = "praw_adSiedzNumerLokalu")
        protected String prawAdSiedzNumerLokalu;
        @XmlElement(name = "praw_adSiedzNietypoweMiejsceLokalizacji")
        protected String prawAdSiedzNietypoweMiejsceLokalizacji;
        @XmlElement(name = "praw_numerTelefonu")
        protected String prawNumerTelefonu;
        @XmlElement(name = "praw_numerWewnetrznyTelefonu")
        protected String prawNumerWewnetrznyTelefonu;
        @XmlElement(name = "praw_numerFaksu")
        protected String prawNumerFaksu;
        @XmlElement(name = "praw_adresEmail")
        protected String prawAdresEmail;
        @XmlElement(name = "praw_adresStronyinternetowej")
        protected String prawAdresStronyinternetowej;
        @XmlElement(name = "praw_adSiedzKraj_Nazwa")
        protected String prawAdSiedzKrajNazwa;
        @XmlElement(name = "praw_adSiedzWojewodztwo_Nazwa")
        protected String prawAdSiedzWojewodztwoNazwa;
        @XmlElement(name = "praw_adSiedzPowiat_Nazwa")
        protected String prawAdSiedzPowiatNazwa;
        @XmlElement(name = "praw_adSiedzGmina_Nazwa")
        protected String prawAdSiedzGminaNazwa;
        @XmlElement(name = "praw_adSiedzMiejscowosc_Nazwa")
        protected String prawAdSiedzMiejscowoscNazwa;
        @XmlElement(name = "praw_adSiedzMiejscowoscPoczty_Nazwa")
        protected String prawAdSiedzMiejscowoscPocztyNazwa;
        @XmlElement(name = "praw_adSiedzUlica_Nazwa")
        protected String prawAdSiedzUlicaNazwa;
        @XmlElement(name = "praw_podstawowaFormaPrawna_Symbol")
        protected String prawPodstawowaFormaPrawnaSymbol;
        @XmlElement(name = "praw_szczegolnaFormaPrawna_Symbol")
        protected String prawSzczegolnaFormaPrawnaSymbol;
        @XmlElement(name = "praw_formaFinansowania_Symbol")
        protected String prawFormaFinansowaniaSymbol;
        @XmlElement(name = "praw_formaWlasnosci_Symbol")
        protected String prawFormaWlasnosciSymbol;
        @XmlElement(name = "praw_organZalozycielski_Symbol")
        protected String prawOrganZalozycielskiSymbol;
        @XmlElement(name = "praw_organRejestrowy_Symbol")
        protected String prawOrganRejestrowySymbol;
        @XmlElement(name = "praw_rodzajRejestruEwidencji_Symbol")
        protected String prawRodzajRejestruEwidencjiSymbol;
        @XmlElement(name = "praw_podstawowaFormaPrawna_Nazwa")
        protected String prawPodstawowaFormaPrawnaNazwa;
        @XmlElement(name = "praw_szczegolnaFormaPrawna_Nazwa")
        protected String prawSzczegolnaFormaPrawnaNazwa;
        @XmlElement(name = "praw_formaFinansowania_Nazwa")
        protected String prawFormaFinansowaniaNazwa;
        @XmlElement(name = "praw_formaWlasnosci_Nazwa")
        protected String prawFormaWlasnosciNazwa;
        @XmlElement(name = "praw_organZalozycielski_Nazwa")
        protected String prawOrganZalozycielskiNazwa;
        @XmlElement(name = "praw_organRejestrowy_Nazwa")
        protected String prawOrganRejestrowyNazwa;
        @XmlElement(name = "praw_rodzajRejestruEwidencji_Nazwa")
        protected String prawRodzajRejestruEwidencjiNazwa;
        @XmlElement(name = "praw_liczbaJednLokalnych")
        protected Integer prawLiczbaJednLokalnych;

        /**
         * Gets the value of the prawRegon9 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawRegon9() {
            return prawRegon9;
        }

        /**
         * Sets the value of the prawRegon9 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawRegon9(String value) {
            this.prawRegon9 = value;
        }

        /**
         * Gets the value of the prawNip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawNip() {
            return prawNip;
        }

        /**
         * Sets the value of the prawNip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawNip(String value) {
            this.prawNip = value;
        }

        /**
         * Gets the value of the prawStatusNip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawStatusNip() {
            return prawStatusNip;
        }

        /**
         * Sets the value of the prawStatusNip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawStatusNip(String value) {
            this.prawStatusNip = value;
        }

        /**
         * Gets the value of the prawNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawNazwa() {
            return prawNazwa;
        }

        /**
         * Sets the value of the prawNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawNazwa(String value) {
            this.prawNazwa = value;
        }

        /**
         * Gets the value of the prawNazwaSkrocona property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawNazwaSkrocona() {
            return prawNazwaSkrocona;
        }

        /**
         * Sets the value of the prawNazwaSkrocona property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawNazwaSkrocona(String value) {
            this.prawNazwaSkrocona = value;
        }

        /**
         * Gets the value of the prawNumerWRejestrzeEwidencji property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawNumerWRejestrzeEwidencji() {
            return prawNumerWRejestrzeEwidencji;
        }

        /**
         * Sets the value of the prawNumerWRejestrzeEwidencji property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawNumerWRejestrzeEwidencji(String value) {
            this.prawNumerWRejestrzeEwidencji = value;
        }

        /**
         * Gets the value of the prawDataWpisuDoRejestruEwidencji property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataWpisuDoRejestruEwidencji() {
            return prawDataWpisuDoRejestruEwidencji;
        }

        /**
         * Sets the value of the prawDataWpisuDoRejestruEwidencji property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataWpisuDoRejestruEwidencji(String value) {
            this.prawDataWpisuDoRejestruEwidencji = value;
        }

        /**
         * Gets the value of the prawDataPowstania property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataPowstania() {
            return prawDataPowstania;
        }

        /**
         * Sets the value of the prawDataPowstania property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataPowstania(String value) {
            this.prawDataPowstania = value;
        }

        /**
         * Gets the value of the prawDataRozpoczeciaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataRozpoczeciaDzialalnosci() {
            return prawDataRozpoczeciaDzialalnosci;
        }

        /**
         * Sets the value of the prawDataRozpoczeciaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataRozpoczeciaDzialalnosci(String value) {
            this.prawDataRozpoczeciaDzialalnosci = value;
        }

        /**
         * Gets the value of the prawDataWpisuDoRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataWpisuDoRegon() {
            return prawDataWpisuDoRegon;
        }

        /**
         * Sets the value of the prawDataWpisuDoRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataWpisuDoRegon(String value) {
            this.prawDataWpisuDoRegon = value;
        }

        /**
         * Gets the value of the prawDataZawieszeniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataZawieszeniaDzialalnosci() {
            return prawDataZawieszeniaDzialalnosci;
        }

        /**
         * Sets the value of the prawDataZawieszeniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataZawieszeniaDzialalnosci(String value) {
            this.prawDataZawieszeniaDzialalnosci = value;
        }

        /**
         * Gets the value of the prawDataWznowieniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataWznowieniaDzialalnosci() {
            return prawDataWznowieniaDzialalnosci;
        }

        /**
         * Sets the value of the prawDataWznowieniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataWznowieniaDzialalnosci(String value) {
            this.prawDataWznowieniaDzialalnosci = value;
        }

        /**
         * Gets the value of the prawDataZaistnieniaZmiany property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataZaistnieniaZmiany() {
            return prawDataZaistnieniaZmiany;
        }

        /**
         * Sets the value of the prawDataZaistnieniaZmiany property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataZaistnieniaZmiany(String value) {
            this.prawDataZaistnieniaZmiany = value;
        }

        /**
         * Gets the value of the prawDataZakonczeniaDzialalnosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataZakonczeniaDzialalnosci() {
            return prawDataZakonczeniaDzialalnosci;
        }

        /**
         * Sets the value of the prawDataZakonczeniaDzialalnosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataZakonczeniaDzialalnosci(String value) {
            this.prawDataZakonczeniaDzialalnosci = value;
        }

        /**
         * Gets the value of the prawDataSkresleniaZRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataSkresleniaZRegon() {
            return prawDataSkresleniaZRegon;
        }

        /**
         * Sets the value of the prawDataSkresleniaZRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataSkresleniaZRegon(String value) {
            this.prawDataSkresleniaZRegon = value;
        }

        /**
         * Gets the value of the prawDataOrzeczeniaOUpadlosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataOrzeczeniaOUpadlosci() {
            return prawDataOrzeczeniaOUpadlosci;
        }

        /**
         * Sets the value of the prawDataOrzeczeniaOUpadlosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataOrzeczeniaOUpadlosci(String value) {
            this.prawDataOrzeczeniaOUpadlosci = value;
        }

        /**
         * Gets the value of the prawDataZakonczeniaPostepowaniaUpadlosciowego property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawDataZakonczeniaPostepowaniaUpadlosciowego() {
            return prawDataZakonczeniaPostepowaniaUpadlosciowego;
        }

        /**
         * Sets the value of the prawDataZakonczeniaPostepowaniaUpadlosciowego property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawDataZakonczeniaPostepowaniaUpadlosciowego(String value) {
            this.prawDataZakonczeniaPostepowaniaUpadlosciowego = value;
        }

        /**
         * Gets the value of the prawAdSiedzKrajSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzKrajSymbol() {
            return prawAdSiedzKrajSymbol;
        }

        /**
         * Sets the value of the prawAdSiedzKrajSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzKrajSymbol(String value) {
            this.prawAdSiedzKrajSymbol = value;
        }

        /**
         * Gets the value of the prawAdSiedzWojewodztwoSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzWojewodztwoSymbol() {
            return prawAdSiedzWojewodztwoSymbol;
        }

        /**
         * Sets the value of the prawAdSiedzWojewodztwoSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzWojewodztwoSymbol(String value) {
            this.prawAdSiedzWojewodztwoSymbol = value;
        }

        /**
         * Gets the value of the prawAdSiedzPowiatSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzPowiatSymbol() {
            return prawAdSiedzPowiatSymbol;
        }

        /**
         * Sets the value of the prawAdSiedzPowiatSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzPowiatSymbol(String value) {
            this.prawAdSiedzPowiatSymbol = value;
        }

        /**
         * Gets the value of the prawAdSiedzGminaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzGminaSymbol() {
            return prawAdSiedzGminaSymbol;
        }

        /**
         * Sets the value of the prawAdSiedzGminaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzGminaSymbol(String value) {
            this.prawAdSiedzGminaSymbol = value;
        }

        /**
         * Gets the value of the prawAdSiedzKodPocztowy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzKodPocztowy() {
            return prawAdSiedzKodPocztowy;
        }

        /**
         * Sets the value of the prawAdSiedzKodPocztowy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzKodPocztowy(String value) {
            this.prawAdSiedzKodPocztowy = value;
        }

        /**
         * Gets the value of the prawAdSiedzMiejscowoscPocztySymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzMiejscowoscPocztySymbol() {
            return prawAdSiedzMiejscowoscPocztySymbol;
        }

        /**
         * Sets the value of the prawAdSiedzMiejscowoscPocztySymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzMiejscowoscPocztySymbol(String value) {
            this.prawAdSiedzMiejscowoscPocztySymbol = value;
        }

        /**
         * Gets the value of the prawAdSiedzMiejscowoscSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzMiejscowoscSymbol() {
            return prawAdSiedzMiejscowoscSymbol;
        }

        /**
         * Sets the value of the prawAdSiedzMiejscowoscSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzMiejscowoscSymbol(String value) {
            this.prawAdSiedzMiejscowoscSymbol = value;
        }

        /**
         * Gets the value of the prawAdSiedzUlicaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzUlicaSymbol() {
            return prawAdSiedzUlicaSymbol;
        }

        /**
         * Sets the value of the prawAdSiedzUlicaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzUlicaSymbol(String value) {
            this.prawAdSiedzUlicaSymbol = value;
        }

        /**
         * Gets the value of the prawAdSiedzNumerNieruchomosci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzNumerNieruchomosci() {
            return prawAdSiedzNumerNieruchomosci;
        }

        /**
         * Sets the value of the prawAdSiedzNumerNieruchomosci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzNumerNieruchomosci(String value) {
            this.prawAdSiedzNumerNieruchomosci = value;
        }

        /**
         * Gets the value of the prawAdSiedzNumerLokalu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzNumerLokalu() {
            return prawAdSiedzNumerLokalu;
        }

        /**
         * Sets the value of the prawAdSiedzNumerLokalu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzNumerLokalu(String value) {
            this.prawAdSiedzNumerLokalu = value;
        }

        /**
         * Gets the value of the prawAdSiedzNietypoweMiejsceLokalizacji property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzNietypoweMiejsceLokalizacji() {
            return prawAdSiedzNietypoweMiejsceLokalizacji;
        }

        /**
         * Sets the value of the prawAdSiedzNietypoweMiejsceLokalizacji property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzNietypoweMiejsceLokalizacji(String value) {
            this.prawAdSiedzNietypoweMiejsceLokalizacji = value;
        }

        /**
         * Gets the value of the prawNumerTelefonu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawNumerTelefonu() {
            return prawNumerTelefonu;
        }

        /**
         * Sets the value of the prawNumerTelefonu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawNumerTelefonu(String value) {
            this.prawNumerTelefonu = value;
        }

        /**
         * Gets the value of the prawNumerWewnetrznyTelefonu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawNumerWewnetrznyTelefonu() {
            return prawNumerWewnetrznyTelefonu;
        }

        /**
         * Sets the value of the prawNumerWewnetrznyTelefonu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawNumerWewnetrznyTelefonu(String value) {
            this.prawNumerWewnetrznyTelefonu = value;
        }

        /**
         * Gets the value of the prawNumerFaksu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawNumerFaksu() {
            return prawNumerFaksu;
        }

        /**
         * Sets the value of the prawNumerFaksu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawNumerFaksu(String value) {
            this.prawNumerFaksu = value;
        }

        /**
         * Gets the value of the prawAdresEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdresEmail() {
            return prawAdresEmail;
        }

        /**
         * Sets the value of the prawAdresEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdresEmail(String value) {
            this.prawAdresEmail = value;
        }

        /**
         * Gets the value of the prawAdresStronyinternetowej property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdresStronyinternetowej() {
            return prawAdresStronyinternetowej;
        }

        /**
         * Sets the value of the prawAdresStronyinternetowej property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdresStronyinternetowej(String value) {
            this.prawAdresStronyinternetowej = value;
        }

        /**
         * Gets the value of the prawAdSiedzKrajNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzKrajNazwa() {
            return prawAdSiedzKrajNazwa;
        }

        /**
         * Sets the value of the prawAdSiedzKrajNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzKrajNazwa(String value) {
            this.prawAdSiedzKrajNazwa = value;
        }

        /**
         * Gets the value of the prawAdSiedzWojewodztwoNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzWojewodztwoNazwa() {
            return prawAdSiedzWojewodztwoNazwa;
        }

        /**
         * Sets the value of the prawAdSiedzWojewodztwoNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzWojewodztwoNazwa(String value) {
            this.prawAdSiedzWojewodztwoNazwa = value;
        }

        /**
         * Gets the value of the prawAdSiedzPowiatNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzPowiatNazwa() {
            return prawAdSiedzPowiatNazwa;
        }

        /**
         * Sets the value of the prawAdSiedzPowiatNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzPowiatNazwa(String value) {
            this.prawAdSiedzPowiatNazwa = value;
        }

        /**
         * Gets the value of the prawAdSiedzGminaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzGminaNazwa() {
            return prawAdSiedzGminaNazwa;
        }

        /**
         * Sets the value of the prawAdSiedzGminaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzGminaNazwa(String value) {
            this.prawAdSiedzGminaNazwa = value;
        }

        /**
         * Gets the value of the prawAdSiedzMiejscowoscNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzMiejscowoscNazwa() {
            return prawAdSiedzMiejscowoscNazwa;
        }

        /**
         * Sets the value of the prawAdSiedzMiejscowoscNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzMiejscowoscNazwa(String value) {
            this.prawAdSiedzMiejscowoscNazwa = value;
        }

        /**
         * Gets the value of the prawAdSiedzMiejscowoscPocztyNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzMiejscowoscPocztyNazwa() {
            return prawAdSiedzMiejscowoscPocztyNazwa;
        }

        /**
         * Sets the value of the prawAdSiedzMiejscowoscPocztyNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzMiejscowoscPocztyNazwa(String value) {
            this.prawAdSiedzMiejscowoscPocztyNazwa = value;
        }

        /**
         * Gets the value of the prawAdSiedzUlicaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawAdSiedzUlicaNazwa() {
            return prawAdSiedzUlicaNazwa;
        }

        /**
         * Sets the value of the prawAdSiedzUlicaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawAdSiedzUlicaNazwa(String value) {
            this.prawAdSiedzUlicaNazwa = value;
        }

        /**
         * Gets the value of the prawPodstawowaFormaPrawnaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawPodstawowaFormaPrawnaSymbol() {
            return prawPodstawowaFormaPrawnaSymbol;
        }

        /**
         * Sets the value of the prawPodstawowaFormaPrawnaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawPodstawowaFormaPrawnaSymbol(String value) {
            this.prawPodstawowaFormaPrawnaSymbol = value;
        }

        /**
         * Gets the value of the prawSzczegolnaFormaPrawnaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawSzczegolnaFormaPrawnaSymbol() {
            return prawSzczegolnaFormaPrawnaSymbol;
        }

        /**
         * Sets the value of the prawSzczegolnaFormaPrawnaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawSzczegolnaFormaPrawnaSymbol(String value) {
            this.prawSzczegolnaFormaPrawnaSymbol = value;
        }

        /**
         * Gets the value of the prawFormaFinansowaniaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawFormaFinansowaniaSymbol() {
            return prawFormaFinansowaniaSymbol;
        }

        /**
         * Sets the value of the prawFormaFinansowaniaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawFormaFinansowaniaSymbol(String value) {
            this.prawFormaFinansowaniaSymbol = value;
        }

        /**
         * Gets the value of the prawFormaWlasnosciSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawFormaWlasnosciSymbol() {
            return prawFormaWlasnosciSymbol;
        }

        /**
         * Sets the value of the prawFormaWlasnosciSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawFormaWlasnosciSymbol(String value) {
            this.prawFormaWlasnosciSymbol = value;
        }

        /**
         * Gets the value of the prawOrganZalozycielskiSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawOrganZalozycielskiSymbol() {
            return prawOrganZalozycielskiSymbol;
        }

        /**
         * Sets the value of the prawOrganZalozycielskiSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawOrganZalozycielskiSymbol(String value) {
            this.prawOrganZalozycielskiSymbol = value;
        }

        /**
         * Gets the value of the prawOrganRejestrowySymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawOrganRejestrowySymbol() {
            return prawOrganRejestrowySymbol;
        }

        /**
         * Sets the value of the prawOrganRejestrowySymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawOrganRejestrowySymbol(String value) {
            this.prawOrganRejestrowySymbol = value;
        }

        /**
         * Gets the value of the prawRodzajRejestruEwidencjiSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawRodzajRejestruEwidencjiSymbol() {
            return prawRodzajRejestruEwidencjiSymbol;
        }

        /**
         * Sets the value of the prawRodzajRejestruEwidencjiSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawRodzajRejestruEwidencjiSymbol(String value) {
            this.prawRodzajRejestruEwidencjiSymbol = value;
        }

        /**
         * Gets the value of the prawPodstawowaFormaPrawnaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawPodstawowaFormaPrawnaNazwa() {
            return prawPodstawowaFormaPrawnaNazwa;
        }

        /**
         * Sets the value of the prawPodstawowaFormaPrawnaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawPodstawowaFormaPrawnaNazwa(String value) {
            this.prawPodstawowaFormaPrawnaNazwa = value;
        }

        /**
         * Gets the value of the prawSzczegolnaFormaPrawnaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawSzczegolnaFormaPrawnaNazwa() {
            return prawSzczegolnaFormaPrawnaNazwa;
        }

        /**
         * Sets the value of the prawSzczegolnaFormaPrawnaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawSzczegolnaFormaPrawnaNazwa(String value) {
            this.prawSzczegolnaFormaPrawnaNazwa = value;
        }

        /**
         * Gets the value of the prawFormaFinansowaniaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawFormaFinansowaniaNazwa() {
            return prawFormaFinansowaniaNazwa;
        }

        /**
         * Sets the value of the prawFormaFinansowaniaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawFormaFinansowaniaNazwa(String value) {
            this.prawFormaFinansowaniaNazwa = value;
        }

        /**
         * Gets the value of the prawFormaWlasnosciNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawFormaWlasnosciNazwa() {
            return prawFormaWlasnosciNazwa;
        }

        /**
         * Sets the value of the prawFormaWlasnosciNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawFormaWlasnosciNazwa(String value) {
            this.prawFormaWlasnosciNazwa = value;
        }

        /**
         * Gets the value of the prawOrganZalozycielskiNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawOrganZalozycielskiNazwa() {
            return prawOrganZalozycielskiNazwa;
        }

        /**
         * Sets the value of the prawOrganZalozycielskiNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawOrganZalozycielskiNazwa(String value) {
            this.prawOrganZalozycielskiNazwa = value;
        }

        /**
         * Gets the value of the prawOrganRejestrowyNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawOrganRejestrowyNazwa() {
            return prawOrganRejestrowyNazwa;
        }

        /**
         * Sets the value of the prawOrganRejestrowyNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawOrganRejestrowyNazwa(String value) {
            this.prawOrganRejestrowyNazwa = value;
        }

        /**
         * Gets the value of the prawRodzajRejestruEwidencjiNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrawRodzajRejestruEwidencjiNazwa() {
            return prawRodzajRejestruEwidencjiNazwa;
        }

        /**
         * Sets the value of the prawRodzajRejestruEwidencjiNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrawRodzajRejestruEwidencjiNazwa(String value) {
            this.prawRodzajRejestruEwidencjiNazwa = value;
        }

        /**
         * Gets the value of the prawLiczbaJednLokalnych property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPrawLiczbaJednLokalnych() {
            return prawLiczbaJednLokalnych;
        }

        /**
         * Sets the value of the prawLiczbaJednLokalnych property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPrawLiczbaJednLokalnych(Integer value) {
            this.prawLiczbaJednLokalnych = value;
        }

    }

}
