//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 05:50:31 PM CET 
//


package com.archu.gussoapintegration.integration.regon.model.fullreport;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dane" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="lokfiz_pkd_Kod" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="5"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_pkd_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_pkd_Przewazajace" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="lokfiz_Silos_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dane"
})
@XmlRootElement(name = "root")
public class JednLokalnaOsFizycznejPkdRoot {

    protected List<JednLokalnaOsFizycznejPkdData> dane;

    /**
     * Gets the value of the dane property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dane property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDane().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JednLokalnaOsFizycznejPkdData }
     * 
     * 
     */
    public List<JednLokalnaOsFizycznejPkdData> getDane() {
        if (dane == null) {
            dane = new ArrayList<JednLokalnaOsFizycznejPkdData>();
        }
        return this.dane;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lokfiz_pkd_Kod" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="5"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_pkd_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_pkd_Przewazajace" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="lokfiz_Silos_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lokfizPkdKod",
        "lokfizPkdNazwa",
        "lokfizPkdPrzewazajace",
        "lokfizSilosSymbol"
    })
    public static class JednLokalnaOsFizycznejPkdData {

        @XmlElement(name = "lokfiz_pkd_Kod")
        protected String lokfizPkdKod;
        @XmlElement(name = "lokfiz_pkd_Nazwa")
        protected String lokfizPkdNazwa;
        @XmlElement(name = "lokfiz_pkd_Przewazajace")
        protected String lokfizPkdPrzewazajace;
        @XmlElement(name = "lokfiz_Silos_Symbol")
        protected String lokfizSilosSymbol;

        /**
         * Gets the value of the lokfizPkdKod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizPkdKod() {
            return lokfizPkdKod;
        }

        /**
         * Sets the value of the lokfizPkdKod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizPkdKod(String value) {
            this.lokfizPkdKod = value;
        }

        /**
         * Gets the value of the lokfizPkdNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizPkdNazwa() {
            return lokfizPkdNazwa;
        }

        /**
         * Sets the value of the lokfizPkdNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizPkdNazwa(String value) {
            this.lokfizPkdNazwa = value;
        }

        /**
         * Gets the value of the lokfizPkdPrzewazajace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizPkdPrzewazajace() {
            return lokfizPkdPrzewazajace;
        }

        /**
         * Sets the value of the lokfizPkdPrzewazajace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizPkdPrzewazajace(String value) {
            this.lokfizPkdPrzewazajace = value;
        }

        /**
         * Gets the value of the lokfizSilosSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokfizSilosSymbol() {
            return lokfizSilosSymbol;
        }

        /**
         * Sets the value of the lokfizSilosSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokfizSilosSymbol(String value) {
            this.lokfizSilosSymbol = value;
        }

    }

}
