//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.23 at 06:09:05 PM CET 
//


package com.archu.gussoapintegration.integration.regon.model.fullreport;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dane"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="fiz_regon9" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="9"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_nip" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_statusNip" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value=""/&gt;
 *                         &lt;enumeration value="Uchylony"/&gt;
 *                         &lt;enumeration value="Unieważniony"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_nazwisko" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_imie1" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="50"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_imie2" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="50"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataWpisuPodmiotuDoRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataZaistnieniaZmiany" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dataSkresleniaPodmiotuZRegon" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_podstawowaFormaPrawna_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_szczegolnaFormaPrawna_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_formaFinansowania_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_formaWlasnosci_Symbol" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="50"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_podstawowaFormaPrawna_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_szczegolnaFormaPrawna_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="200"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_formaFinansowania_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="240"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_formaWlasnosci_Nazwa" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="240"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dzialalnoscCeidg" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dzialalnoscRolnicza" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dzialalnoscPozostala" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_dzialalnoscSkreslonaDo20141108" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiz_liczbaJednLokalnych" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dane"
})
@XmlRootElement(name = "root")
public class OsFizycznaDaneOgolneRoot {

    @XmlElement(required = true)
    protected OsFizycznaDaneOgolneData dane;

    /**
     * Gets the value of the dane property.
     * 
     * @return
     *     possible object is
     *     {@link OsFizycznaDaneOgolneData }
     *     
     */
    public OsFizycznaDaneOgolneData getDane() {
        return dane;
    }

    /**
     * Sets the value of the dane property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsFizycznaDaneOgolneData }
     *     
     */
    public void setDane(OsFizycznaDaneOgolneData value) {
        this.dane = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="fiz_regon9" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="9"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_nip" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_statusNip" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value=""/&gt;
     *               &lt;enumeration value="Uchylony"/&gt;
     *               &lt;enumeration value="Unieważniony"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_nazwisko" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_imie1" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="50"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_imie2" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="50"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataWpisuPodmiotuDoRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataZaistnieniaZmiany" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dataSkresleniaPodmiotuZRegon" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_podstawowaFormaPrawna_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_szczegolnaFormaPrawna_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_formaFinansowania_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_formaWlasnosci_Symbol" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="50"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_podstawowaFormaPrawna_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_szczegolnaFormaPrawna_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="200"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_formaFinansowania_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="240"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_formaWlasnosci_Nazwa" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="240"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dzialalnoscCeidg" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dzialalnoscRolnicza" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dzialalnoscPozostala" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_dzialalnoscSkreslonaDo20141108" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiz_liczbaJednLokalnych" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fizRegon9",
        "fizNip",
        "fizStatusNip",
        "fizNazwisko",
        "fizImie1",
        "fizImie2",
        "fizDataWpisuPodmiotuDoRegon",
        "fizDataZaistnieniaZmiany",
        "fizDataSkresleniaPodmiotuZRegon",
        "fizPodstawowaFormaPrawnaSymbol",
        "fizSzczegolnaFormaPrawnaSymbol",
        "fizFormaFinansowaniaSymbol",
        "fizFormaWlasnosciSymbol",
        "fizPodstawowaFormaPrawnaNazwa",
        "fizSzczegolnaFormaPrawnaNazwa",
        "fizFormaFinansowaniaNazwa",
        "fizFormaWlasnosciNazwa",
        "fizDzialalnoscCeidg",
        "fizDzialalnoscRolnicza",
        "fizDzialalnoscPozostala",
        "fizDzialalnoscSkreslonaDo20141108",
        "fizLiczbaJednLokalnych"
    })
    public static class OsFizycznaDaneOgolneData {

        @XmlElement(name = "fiz_regon9")
        protected String fizRegon9;
        @XmlElement(name = "fiz_nip")
        protected String fizNip;
        @XmlElement(name = "fiz_statusNip")
        protected String fizStatusNip;
        @XmlElement(name = "fiz_nazwisko")
        protected String fizNazwisko;
        @XmlElement(name = "fiz_imie1")
        protected String fizImie1;
        @XmlElement(name = "fiz_imie2")
        protected String fizImie2;
        @XmlElement(name = "fiz_dataWpisuPodmiotuDoRegon")
        protected String fizDataWpisuPodmiotuDoRegon;
        @XmlElement(name = "fiz_dataZaistnieniaZmiany")
        protected String fizDataZaistnieniaZmiany;
        @XmlElement(name = "fiz_dataSkresleniaPodmiotuZRegon")
        protected String fizDataSkresleniaPodmiotuZRegon;
        @XmlElement(name = "fiz_podstawowaFormaPrawna_Symbol")
        protected String fizPodstawowaFormaPrawnaSymbol;
        @XmlElement(name = "fiz_szczegolnaFormaPrawna_Symbol")
        protected String fizSzczegolnaFormaPrawnaSymbol;
        @XmlElement(name = "fiz_formaFinansowania_Symbol")
        protected String fizFormaFinansowaniaSymbol;
        @XmlElement(name = "fiz_formaWlasnosci_Symbol")
        protected String fizFormaWlasnosciSymbol;
        @XmlElement(name = "fiz_podstawowaFormaPrawna_Nazwa")
        protected String fizPodstawowaFormaPrawnaNazwa;
        @XmlElement(name = "fiz_szczegolnaFormaPrawna_Nazwa")
        protected String fizSzczegolnaFormaPrawnaNazwa;
        @XmlElement(name = "fiz_formaFinansowania_Nazwa")
        protected String fizFormaFinansowaniaNazwa;
        @XmlElement(name = "fiz_formaWlasnosci_Nazwa")
        protected String fizFormaWlasnosciNazwa;
        @XmlElement(name = "fiz_dzialalnoscCeidg")
        protected Integer fizDzialalnoscCeidg;
        @XmlElement(name = "fiz_dzialalnoscRolnicza")
        protected Integer fizDzialalnoscRolnicza;
        @XmlElement(name = "fiz_dzialalnoscPozostala")
        protected Integer fizDzialalnoscPozostala;
        @XmlElement(name = "fiz_dzialalnoscSkreslonaDo20141108")
        protected Integer fizDzialalnoscSkreslonaDo20141108;
        @XmlElement(name = "fiz_liczbaJednLokalnych")
        protected Integer fizLiczbaJednLokalnych;

        /**
         * Gets the value of the fizRegon9 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizRegon9() {
            return fizRegon9;
        }

        /**
         * Sets the value of the fizRegon9 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizRegon9(String value) {
            this.fizRegon9 = value;
        }

        /**
         * Gets the value of the fizNip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizNip() {
            return fizNip;
        }

        /**
         * Sets the value of the fizNip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizNip(String value) {
            this.fizNip = value;
        }

        /**
         * Gets the value of the fizStatusNip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizStatusNip() {
            return fizStatusNip;
        }

        /**
         * Sets the value of the fizStatusNip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizStatusNip(String value) {
            this.fizStatusNip = value;
        }

        /**
         * Gets the value of the fizNazwisko property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizNazwisko() {
            return fizNazwisko;
        }

        /**
         * Sets the value of the fizNazwisko property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizNazwisko(String value) {
            this.fizNazwisko = value;
        }

        /**
         * Gets the value of the fizImie1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizImie1() {
            return fizImie1;
        }

        /**
         * Sets the value of the fizImie1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizImie1(String value) {
            this.fizImie1 = value;
        }

        /**
         * Gets the value of the fizImie2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizImie2() {
            return fizImie2;
        }

        /**
         * Sets the value of the fizImie2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizImie2(String value) {
            this.fizImie2 = value;
        }

        /**
         * Gets the value of the fizDataWpisuPodmiotuDoRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataWpisuPodmiotuDoRegon() {
            return fizDataWpisuPodmiotuDoRegon;
        }

        /**
         * Sets the value of the fizDataWpisuPodmiotuDoRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataWpisuPodmiotuDoRegon(String value) {
            this.fizDataWpisuPodmiotuDoRegon = value;
        }

        /**
         * Gets the value of the fizDataZaistnieniaZmiany property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataZaistnieniaZmiany() {
            return fizDataZaistnieniaZmiany;
        }

        /**
         * Sets the value of the fizDataZaistnieniaZmiany property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataZaistnieniaZmiany(String value) {
            this.fizDataZaistnieniaZmiany = value;
        }

        /**
         * Gets the value of the fizDataSkresleniaPodmiotuZRegon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizDataSkresleniaPodmiotuZRegon() {
            return fizDataSkresleniaPodmiotuZRegon;
        }

        /**
         * Sets the value of the fizDataSkresleniaPodmiotuZRegon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizDataSkresleniaPodmiotuZRegon(String value) {
            this.fizDataSkresleniaPodmiotuZRegon = value;
        }

        /**
         * Gets the value of the fizPodstawowaFormaPrawnaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizPodstawowaFormaPrawnaSymbol() {
            return fizPodstawowaFormaPrawnaSymbol;
        }

        /**
         * Sets the value of the fizPodstawowaFormaPrawnaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizPodstawowaFormaPrawnaSymbol(String value) {
            this.fizPodstawowaFormaPrawnaSymbol = value;
        }

        /**
         * Gets the value of the fizSzczegolnaFormaPrawnaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizSzczegolnaFormaPrawnaSymbol() {
            return fizSzczegolnaFormaPrawnaSymbol;
        }

        /**
         * Sets the value of the fizSzczegolnaFormaPrawnaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizSzczegolnaFormaPrawnaSymbol(String value) {
            this.fizSzczegolnaFormaPrawnaSymbol = value;
        }

        /**
         * Gets the value of the fizFormaFinansowaniaSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizFormaFinansowaniaSymbol() {
            return fizFormaFinansowaniaSymbol;
        }

        /**
         * Sets the value of the fizFormaFinansowaniaSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizFormaFinansowaniaSymbol(String value) {
            this.fizFormaFinansowaniaSymbol = value;
        }

        /**
         * Gets the value of the fizFormaWlasnosciSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizFormaWlasnosciSymbol() {
            return fizFormaWlasnosciSymbol;
        }

        /**
         * Sets the value of the fizFormaWlasnosciSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizFormaWlasnosciSymbol(String value) {
            this.fizFormaWlasnosciSymbol = value;
        }

        /**
         * Gets the value of the fizPodstawowaFormaPrawnaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizPodstawowaFormaPrawnaNazwa() {
            return fizPodstawowaFormaPrawnaNazwa;
        }

        /**
         * Sets the value of the fizPodstawowaFormaPrawnaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizPodstawowaFormaPrawnaNazwa(String value) {
            this.fizPodstawowaFormaPrawnaNazwa = value;
        }

        /**
         * Gets the value of the fizSzczegolnaFormaPrawnaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizSzczegolnaFormaPrawnaNazwa() {
            return fizSzczegolnaFormaPrawnaNazwa;
        }

        /**
         * Sets the value of the fizSzczegolnaFormaPrawnaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizSzczegolnaFormaPrawnaNazwa(String value) {
            this.fizSzczegolnaFormaPrawnaNazwa = value;
        }

        /**
         * Gets the value of the fizFormaFinansowaniaNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizFormaFinansowaniaNazwa() {
            return fizFormaFinansowaniaNazwa;
        }

        /**
         * Sets the value of the fizFormaFinansowaniaNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizFormaFinansowaniaNazwa(String value) {
            this.fizFormaFinansowaniaNazwa = value;
        }

        /**
         * Gets the value of the fizFormaWlasnosciNazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFizFormaWlasnosciNazwa() {
            return fizFormaWlasnosciNazwa;
        }

        /**
         * Sets the value of the fizFormaWlasnosciNazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFizFormaWlasnosciNazwa(String value) {
            this.fizFormaWlasnosciNazwa = value;
        }

        /**
         * Gets the value of the fizDzialalnoscCeidg property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFizDzialalnoscCeidg() {
            return fizDzialalnoscCeidg;
        }

        /**
         * Sets the value of the fizDzialalnoscCeidg property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFizDzialalnoscCeidg(Integer value) {
            this.fizDzialalnoscCeidg = value;
        }

        /**
         * Gets the value of the fizDzialalnoscRolnicza property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFizDzialalnoscRolnicza() {
            return fizDzialalnoscRolnicza;
        }

        /**
         * Sets the value of the fizDzialalnoscRolnicza property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFizDzialalnoscRolnicza(Integer value) {
            this.fizDzialalnoscRolnicza = value;
        }

        /**
         * Gets the value of the fizDzialalnoscPozostala property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFizDzialalnoscPozostala() {
            return fizDzialalnoscPozostala;
        }

        /**
         * Sets the value of the fizDzialalnoscPozostala property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFizDzialalnoscPozostala(Integer value) {
            this.fizDzialalnoscPozostala = value;
        }

        /**
         * Gets the value of the fizDzialalnoscSkreslonaDo20141108 property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFizDzialalnoscSkreslonaDo20141108() {
            return fizDzialalnoscSkreslonaDo20141108;
        }

        /**
         * Sets the value of the fizDzialalnoscSkreslonaDo20141108 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFizDzialalnoscSkreslonaDo20141108(Integer value) {
            this.fizDzialalnoscSkreslonaDo20141108 = value;
        }

        /**
         * Gets the value of the fizLiczbaJednLokalnych property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFizLiczbaJednLokalnych() {
            return fizLiczbaJednLokalnych;
        }

        /**
         * Sets the value of the fizLiczbaJednLokalnych property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFizLiczbaJednLokalnych(Integer value) {
            this.fizLiczbaJednLokalnych = value;
        }

    }

}
