//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.03 at 05:33:41 PM CET 
//


package com.archu.gussoapintegration.gus.regon;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pParametryWyszukiwania" type="{http://CIS/BIR/PUBL/2014/07/DataContract}ParametryWyszukiwania" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pParametryWyszukiwania"
})
@XmlRootElement(name = "DaneSzukajPodmioty")
public class DaneSzukajPodmioty {

    @XmlElementRef(name = "pParametryWyszukiwania", namespace = "http://CIS/BIR/PUBL/2014/07", type = JAXBElement.class, required = false)
    protected JAXBElement<ParametryWyszukiwania> pParametryWyszukiwania;

    /**
     * Gets the value of the pParametryWyszukiwania property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ParametryWyszukiwania }{@code >}
     *     
     */
    public JAXBElement<ParametryWyszukiwania> getPParametryWyszukiwania() {
        return pParametryWyszukiwania;
    }

    /**
     * Sets the value of the pParametryWyszukiwania property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ParametryWyszukiwania }{@code >}
     *     
     */
    public void setPParametryWyszukiwania(JAXBElement<ParametryWyszukiwania> value) {
        this.pParametryWyszukiwania = value;
    }

}
